### ISSUE TITLE
docs: Remove topics list from the "How to Contribute to Open Source" section 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#101]
## Description

The "How to Contribute to Open Source" section has a list of topics that contain the titles of the sections and subsections. But we don't need this because we have a sidebar that holds these titles and serves as a Table of Contents.

## Propose Solution

Remove the list in the [How to Contribute to Open Source](http://localhost:3000/#/05-how-to-contribute-to-open-source?id=how-to-contribute-to-open-source) section.

### Codeblocks

https://github.com/open-sauced/intro/blob/b4c530840309b923fed26473b40c787d85f48cd1/05-how-to-contribute-to-open-source.md?plain=1#L3-L8

---

_Originally posted by @adiati98 in https://github.com/open-sauced/intro/pull/100#discussion_r1431921267_

**Comment by Kenny4297** [comment]
Hi @adiati98, may I be assigned to this issue?

**Comment by adiati98** [comment]
@Kenny4297 it's all you!
