### ISSUE TITLE
Docs: Add steps to create issue and make screenshot of profile on the README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#103]
## Background

- We want contributors to learn how to create an issue as part of contributing flow.
- To prevent mistakes of not running the command to generate the profile, we want to ensure contributors providing a screenshot of their profile on the README after being generated to be included in their PRs.

## Suggested solution

In the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section:

- [x] Add step 1 to create an issue.

> 1. Create an issue by clicking the "New issue" button in the "Issues" tab and complete the form.

- [x] Add a step to make a screenshot right after the step to "Run `npm run contributors:generate` in your terminal to generate the guest book on the README.".

> X. Copy and paste the Markdown of the README in [Markdown Live Preview](https://markdownlivepreview.com/) and take a screenshot of your profile being generated. You will need this later when creating a pull request. **Tips**: If you don't see your profile in the "Contributors" section, zoom out the screen until you can see it before taking a screenshot.
  
- [x] Fix the numbering of the steps accordingly.
- [x] Check the code and the live preview format of the section. You can use [Markdown Live Preview](https://markdownlivepreview.com/) to live preview the Markdown. 

Below is the code block of the "Getting Started" section:

https://github.com/open-sauced/intro/blob/a5a10bf39a6c32bc56868aaf973f3ddd60881be6/05-how-to-contribute-to-open-source.md?plain=1#L140-L239

**Comment by rd-sharma7** [comment]
Can I solve that one?

**Comment by at-the-vr** [comment]
I think I got the idea, can I take this Issue 😄

**Comment by CBID2** [comment]
> I think I got the idea, can I take this Issue 😄

Go ahead @at-the-vr! :)
