### ISSUE TITLE
Bug: Adjust heading levels and give space before and after each heading as Markdown best practice

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#107]
### Describe the bug

- In the [Types of contributions](https://intro.opensauced.pizza/#/07-types-of-contributions?id=types-of-contributions) chapter, there are some subheadings that are not in the correct levels.
- There is no space after a heading in some sections. Putting a blank line before and after a heading is one of the [headings best practice in Markdown](https://www.markdownguide.org/basic-syntax/#heading-best-practices).

### Suggested Solution

 Fix the level headings and add a blank line after each heading as below:

- [ ] Change below lines from `h3` to `h4`
   
  https://github.com/open-sauced/intro/blob/c2aca413850ac85bf400ff1c346dba18943dbe39/07-types-of-contributions.md?plain=1#L19

  https://github.com/open-sauced/intro/blob/c2aca413850ac85bf400ff1c346dba18943dbe39/07-types-of-contributions.md?plain=1#L68

- [ ] Change below lines from `h4` to `h5`

  https://github.com/open-sauced/intro/blob/c2aca413850ac85bf400ff1c346dba18943dbe39/07-types-of-contributions.md?plain=1#L29

- [ ] Make sure that there is one blank line before and after each heading. For example:

   https://github.com/open-sauced/intro/blob/c2aca413850ac85bf400ff1c346dba18943dbe39/07-types-of-contributions.md?plain=1#L17-L20

  This should be:

  ```suggestion
  This involves creating, improving, or maintaining the written resources that accompany open-source software projects. Documentation is crucial to open-source projects. It can make a project more accessible and user-friendly, and it can help attract new contributors and encourage repeat contributions.

  ### How to Contribute to Documentation
  
  *If you're interested in contributing to documentation, here are a few tips:*
  ```

**Please include these checklist boxes in your pull request**.

### Steps to reproduce

1. Open the `07-types-of-contributions.md` on your code editor.
2. You will see the inconsistency.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by at-the-vr** [comment]
I would like to take this Issue

**Comment by adiati98** [comment]
Hey @at-the-vr ,
Thank you for your interest in this issue, and we appreciate all your contributions lately!

We'd like to give someone new a chance to take on this, but keep checking back as we post new issues frequently. 😊

**Comment by asaki222** [comment]
I would like to take this issue!

**Comment by adiati98** [comment]
@asaki222, it's yours. 👍
