### ISSUE TITLE
Bug: Create consistency with "open source" term

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#109]
### Describe the bug

Currently, we have "open-source" and "open source" term in the course and we want to have consistency throughout the repo.

### Suggested solution

Except for file names, let's use "open source" (without hypen) term throughout the course.

### Steps to reproduce

1. Open the repo.
2. Search for "open-source" in each chapter file.
3. You will find this term in most of the chapters.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by flushthemoney** [comment]
I would like to help with this issue, please assign it to me

**Comment by CBID2** [comment]
> I would like to help with this issue, please assign it to me

You're assigned @flushthemoney
