### ISSUE TITLE
Feature: Add gif of the terminal showing the user add themselves using the CLI

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#112]
### Type of feature

🍕 Feature

### Current behavior

We only have written directions. 

### Suggested solution

1. Record a gif of the terminal as you go through the commands to add yourself to the guestbook using the CLI shared in chapter 5.
2. Add the gif to `assets/images` with the name `cli-tool.gif`
3. On line 161 in [chapter 5](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md), add the gif below this text:

```
   **CLI Tool**

   - Run `npm run contributors:add` in your terminal.

     Follow the instructions to add yourself to the guestbook. After you finish and click enter, you must click enter again to confirm your choices.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Pondy007** [comment]
.take
