### ISSUE TITLE
Feature: Reorganize directions for contributors

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#113]
### Type of feature

🍕 Feature

### Current behavior

Right now, we kind of have the directions combined for the CLI and the Manual add. It gets a little confusing because contributors who are using the CLI tool are missing the steps at the end. 

### Suggested solution

I propose that we make `CLI Tool` and `Manual Addition` h4s (####). 

After the last line in the CLI Tool section, we add: Proceed to step seven to complete the process of adding yourself to the guestbook. It would be great if we could find a way to link to step 7.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
That's a good idea @BekahHW! 😊
