### ISSUE TITLE
Feature:  Making changes to directions in Let's Get Practical section

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#114]
### Type of feature

🍕 Feature

### Current behavior

For the activity in the [Let's Get Practical section](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical), there has been two recurring themes:
1. Contributors using the CLI Tool method to submit their profile. 
2. Contributors are not running `npm run contributors:add`and `npm run contributors:generate`commands to generate their profile in the guestbook.

After discussing this with @adiati98 and @BekahHW, we've come to the realization that giving contributors the option to either use the CLI tool or doing it manual is causing this confusion.  

We also noticed that people are not contributing to the pizza-verse repo in spite of our promotion efforts, making it difficult for us to achieve OpenSauced's goal to create a contribution pathway for people to grow in their open source journey. 

### Suggested solution
For the first part of the issue, we having the following solution:

- [ ] Go the ["Manual Selection" section in step 5](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md).
- [ ] Delete the directions:

 https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L162-L211

- [ ] Go to step 6:
https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L147
- [ ] Replace it with the following statement: 
`6. Add yourself to the guestbook with the CLI tool`

- [ ] Go to the next paragraph and delete it: 
https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L149-L156

For the second half of the issue, do the following to add a section about our [pizza-verse repo](https://github.com/open-sauced/pizza-verse/blob/main/README.md) in the [Let's Practical Section](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md):
- [ ]  Go this line: https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L245
- [ ] Add the following statement next to it:
`If you're ready for your next contribution, head on over to the [pizza-verse repo](https://github.com/open-sauced/pizza-verse) and follow the contribution guidelines for your next contribution. Once you're done, head on over to chapter 6 in this course.`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
Hey @CBID2 can you link to the file and the line you're talking about?

Also, please include more info on pizza-verse as we discussed.

**Comment by CBID2** [comment]
> Hey @CBID2 can you link to the file and the line you're talking about?
> 
> Also, please include more info on pizza-verse as we discussed.

Made the changes @BekahHW.

**Comment by BekahHW** [comment]
Can you link to the file in the repo you want them to change rather than in the intro.OpenSauced.pizza site please?

**Comment by CBID2** [comment]
> Can you link to the file in the repo you want them to change rather than in the intro.OpenSauced.pizza site please?

Done @BekahHW

**Comment by BekahHW** [comment]
Let's make this more optional. Instead of suggesting:

> Turn "Congratulations on your first contribution! 🎉" into "Yay you made it! 🎉" Now, you're ready for next contribution: Head on over to the pizza-verse repo and repeat the exact steps to make your contribution to this repository.

Let's do this

> "Congratulations on your first contribution! 🎉 If you're ready for your next contribution, head on over to the [pizza-verse repo](github.com/open-sauced/pizza-verse) and follow the contribution guidelines for your next contribution. Once you're done, head on over to chapter five in this course."

**Comment by CBID2** [comment]
> Let's make this more optional. Instead of suggesting:
> 
> > Turn "Congratulations on your first contribution! 🎉" into "Yay you made it! 🎉" Now, you're ready for next contribution: Head on over to the pizza-verse repo and repeat the exact steps to make your contribution to this repository.
> 
> Let's do this
> 
> > "Congratulations on your first contribution! 🎉 If you're ready for your next contribution, head on over to the [pizza-verse repo](github.com/open-sauced/pizza-verse) and follow the contribution guidelines for your next contribution. Once you're done, head on over to chapter five in this course."

Good idea! :)

**Comment by CBID2** [comment]
> Let's make this more optional. Instead of suggesting:
> 
> > Turn "Congratulations on your first contribution! 🎉" into "Yay you made it! 🎉" Now, you're ready for next contribution: Head on over to the pizza-verse repo and repeat the exact steps to make your contribution to this repository.
> 
> Let's do this
> 
> > "Congratulations on your first contribution! 🎉 If you're ready for your next contribution, head on over to the [pizza-verse repo](github.com/open-sauced/pizza-verse) and follow the contribution guidelines for your next contribution. Once you're done, head on over to chapter five in this course."

**Comment by adiati98** [comment]
@CBID2 as this is a good first issue, can you please point both suggestions to the file and code snippet that need to be changed by [creating a permalink](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)?
This would make easier for first-time contributors to go to the exact file and line of codes. 

See issue #107 for example.

**Comment by adiati98** [comment]
@CBID2 I'd say, instead of:

> 6. Add yourself to the guestbook. Here’s how: 
Do `run contributors:add` in your terminal.
>
> Follow the instructions to add yourself to the guestbook. After you finish and click enter, you must click enter again to confirm your choices.

Let's go with this:

> 6. Add yourself to the guestbook with the CLI tool:

Then remove:

> There are two ways you can complete this activity:
> 
> Using the CLI tool.
> Manually editing the .all-contributorsrc file.
> Although adding yourself to the guestbook with the CLI tool is simpler, we recommend manually editing the file to get more experience adding and committing your changes, creating pull requests, and pull request reviews. Below, you'll find the directions for each method:
>
> CLI Tool

**Comment by CBID2** [comment]
> @CBID2 I'd say, instead of:
> 
> > 6. Add yourself to the guestbook. Here’s how:
> >    Do `run contributors:add` in your terminal.
> > 
> > Follow the instructions to add yourself to the guestbook. After you finish and click enter, you must click enter again to confirm your choices.
> 
> Let's go with this:
> 
> > 6. Add yourself to the guestbook with the CLI tool:
> 
> Then remove:
> 
> > There are two ways you can complete this activity:
> > 
> > * Using the CLI tool.
> > * Manually editing the .all-contributorsrc file.
> > 
> > Although adding yourself to the guestbook with the CLI tool is simpler, we recommend manually editing the file to get more experience adding and committing your changes, creating pull requests, and pull request reviews. Below, you'll find the directions for each method:
> > CLI Tool

Done @adiati98

**Comment by adiati98** [comment]
> > @CBID2 I'd say, instead of:
> > > 6. Add yourself to the guestbook. Here’s how:
> > >    Do `run contributors:add` in your terminal.
> > > 
> > > Follow the instructions to add yourself to the guestbook. After you finish and click enter, you must click enter again to confirm your choices.
> > 
> > 
> > Let's go with this:
> > > 6. Add yourself to the guestbook with the CLI tool:
> > 
> > 
> > Then remove:
> > > There are two ways you can complete this activity:
> > > 
> > > * Using the CLI tool.
> > > * Manually editing the .all-contributorsrc file.
> > > 
> > > Although adding yourself to the guestbook with the CLI tool is simpler, we recommend manually editing the file to get more experience adding and committing your changes, creating pull requests, and pull request reviews. Below, you'll find the directions for each method:
> > > CLI Tool
> 
> Done @adiati98

You haven't added the part that needs to be removed, @CBID2.

**Comment by CBID2** [comment]
> > > @CBID2 I'd say, instead of:
> > > > 6. Add yourself to the guestbook. Here’s how:
> > > >    Do `run contributors:add` in your terminal.
> > > > 
> > > > Follow the instructions to add yourself to the guestbook. After you finish and click enter, you must click enter again to confirm your choices.
> > > 
> > > 
> > > Let's go with this:
> > > > 6. Add yourself to the guestbook with the CLI tool:
> > > 
> > > 
> > > Then remove:
> > > > There are two ways you can complete this activity:
> > > > 
> > > > * Using the CLI tool.
> > > > * Manually editing the .all-contributorsrc file.
> > > > 
> > > > Although adding yourself to the guestbook with the CLI tool is simpler, we recommend manually editing the file to get more experience adding and committing your changes, creating pull requests, and pull request reviews. Below, you'll find the directions for each method:
> > > > CLI Tool
> > 
> > 
> > Done @adiati98
> 
> You haven't added the part that needs to be removed, @CBID2.

I mentioned it in the second checkbox (it says “Delete the following information”). The lines are a permalink

**Comment by adiati98** [comment]
@CBID2 that means we haven't removed the manual instruction.

There are two parts to be deleted:

1. Paragraphs that need to be adjusted. 
   https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L149-L156
2. Manual instruction
   https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L162-L211

And looking closely to the instruction, I think step 9 and 10 also needs to be adjusted.
Can you please double check to what else need to be done here? In the meantime, I add the `needs triage` label until this is finalized. Thanks!

**Comment by BekahHW** [comment]
When you're updating the info Ayu suggested, please update this link `https://github.localhost/github.com/open-sauced/pizza-verse` as well. It should be `https://github.com/open-sauced/pizza-verse`.

**Comment by CBID2** [comment]
Hey @adiati98.  I decided to assign myself to the issue. It’ll be easier for use to continue the conversation that way.

**Comment by CBID2** [comment]
> @CBID2 that means we haven't removed the manual instruction.
> 
> * There are two parts to be deleted:
>   
>   1. Paragraphs that need to be adjusted.
>      https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L149-L156
>   2. Manual instruction
>      https://github.com/open-sauced/intro/blob/4577a767191b640d3092b61a2c687c864fe96356/05-how-to-contribute-to-open-source.md?plain=1#L162-L211
> * Looking closely to the instruction, I think step 9 and 10 also needs to be adjusted.
> 
> Can you please double check to what else need to be done here? In the meantime, I add the `needs triage` label until this is finalized. Thanks!

Hi @adiati98 steps 9 and 10 definitely need to be revised.

**Comment by nickaldwin** [comment]
Hi can i work on this issue?

**Comment by CBID2** [comment]
> Hi, I'm interested can i work on this issue?

Hi @nickaldwin. I'm doing a better version of this issue, so I'm going to close this one. Be on the lookout for it.
