### ISSUE TITLE
Feature: Add Community Translations Section

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#117]
## Type of feature

🍕 Feature

## Current behavior

Although it's not possible for OpenSauced to create and maintain all requested translations, we value community translation contributions.

To recognize these contributions and let our users know that we are not specifically maintaining them, we want to create a space for those willing to maintain translations in any language outside OpenSauced official translations to link to their translations.

_original issue by @BekahHW: https://github.com/open-sauced/intro/issues/71#issue-1935780130_

### Create New File

- [ ] Create `community-translations.md` at the root of the repo. In that file, create the following:

   ```markdown
   # Community Course Translations

   We are grateful for the contributions of the community in translating this course. Although the OpenSauced team does not currently maintain these projects, we want to share the forked copy of the repositories with those taking the course. Below, you will find the latest community translations.
   ```

### Adjustment

With a new file added, some content need to be adjusted in two files:

#### 1. README

- [ ] Adjust the "Language Support" section in the README as follow:

   ```markdown
   ## Language Support

   Like pizza, open source is meant to be shared with everyone. We provide and maintain translations in languages below as our official translations:

   - [French](./translations/fr/README.md)

   For translations in other languages that are maintained by our community, please go to the [Community Translations](link to community-translations.md) section.
   ```

   **Code snippet:**
   https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/README.md?plain=1#L11-L16

#### 2. `i18n-guidelines.md`

- [ ] Change the word "OSS" to "Open Source".
- [ ] Add the link to the Community Translation section.

```diff
- We can't always support the maintenance of translations. However, we know some contributors are willing to translate, and we value these contributions. For that reason, we have a Community Translations section.
-
- If you're interested in translating our Intro to OSS course, fork this repository and add the translation to your forked repository. Then, you can add a link to your translation in the `community-translations.md` file.
-
+ We can't always support the maintenance of translations. However, we know some contributors are willing to translate, and we value these contributions. For that reason, we have a [Community Translations](link to the section) section.
+
+ If you're interested in translating our Intro to Open Source course, fork this repository and add the translation to your forked repository. Then, you can add a link to your translation in the `community-translations.md` file that you can find in the root directory.
+
```

**Code snippet:**
https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/i18n-guidelines.md?plain=1#L28-L30

## Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by vivitt** [comment]
.take

**Comment by adiati98** [comment]
@vivitt checking in here. 😊

How's the progress for this issue? Do you need any help?
