### ISSUE TITLE
Bug: Fix wording in the "Intro" section

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#118]
### Describe the bug

Currently, we have these in the "Intro" section:

- The intro sentence is: "Welcome to the "Getting Started with Open Source" course!"
   But our course's name is "Intro to Open Source with OpenSauced". 
- A section with the title "LFG".
   This title is non-inclusive, as non-native English speakers might not know what it stands for without googling.

So, we need to change these.

### Suggested Solutions

- [ ] Change the intro sentence.
  
   ```diff
   - Welcome to the "Getting Started with Open Source" course!
   + Welcome to the "Intro to Open Source with OpenSauced" course!
   ```

   **Code snippet:**
   https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md?plain=1#L3

- [ ] Change the title "LFG 🚀 " to "Let's Get Started 🚀 "

   ```diff
   - ## LFG 🚀
   + ## Let's Get Started 🚀
   ```

   **Code snippet:**
   https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md?plain=1#L53

### Steps to reproduce

1. Open the [`01-intro.md`](https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md).
2. See the intro sentence and the title of the last section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by MohitKambli** [comment]
.take
