### ISSUE TITLE
Bug: Chapter 5 git clone command typo

### ISSUE THREAD

**Issue by alishata128** [open-sauced/intro#12]
### Describe the bug

In Chapter 5, part of practical contribution to opensauced-guestbook, there is a typo in the git clone command 
```
git clone git@github.com:[your_username]/opensauced-guestbook.git
```
**opensauced-guestbook.git** is not the correct name for the forked repo

### Steps to reproduce

1. Go to File *05-how-to-contribute-to-open-source.md*
2. Edit the File
3. Change the repo name from **"opensauced-guestbook.git"** to **"opensauced-guestbook"**
4. Save the file and commit the changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by kabszac** [comment]
has someone worked on this issue? If not I would like to work on it.

**Comment by alishata128** [comment]
I've worked on this issue, and made a pull request for it, appreciate your help

**Comment by gpsakthivel** [comment]
@alishata128 

Good job mate. 

Note: The mentioned typo issue is occured in two places of this file. 
- Line no: 64
- Line no: 111

Hope your PR contains changes in both the lines.
