### ISSUE TITLE
Bug: Text repeated twice on french translation

### ISSUE THREAD

**Issue by Pondy007** [open-sauced/intro#122]
### Describe the bug

Hi everyone (this is my first time reporting an issue on github) !
On the french translation, chapter 2, the text is repeated twice. From line 71 to 139.
One should remove it.

### Steps to reproduce

1. Go to https://github.com/open-sauced/intro/blob/main/translations/fr/02-qu-est-ce-que-l-open-source.md
2. See that same text is repeated beginning from line 71 to 139

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
I just assigned you the issue @Pondy007
