### ISSUE TITLE
Bug: Fix links, capitalization and wording adjustment in the "Tools to be Successful" chapter

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#129]
### Describe the bug

Below are some things we need to fix in the `04-tools-to-be-successful.md` file:

- Capitalize the main title.
- Wrap texts with the links instead of having independent links.
- Some wording adjustment.

#### Capitalize the main title

- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L1

   ```diff
   - # Tools to be successful
   + # Tools to be Successful 
   ```

#### Wrap texts with the URL

Follow below format to do this and wrap the text that make sense to the link:

```markdown
[text here](URL)
```

- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L41
- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L111
- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L122

#### Wording adjustments

- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L6

   Replace with:

   ```markdown
   - Visual Studio Code (VS Code)
   ```

- [ ] https://github.com/open-sauced/intro/blob/46864456151e9d84cf9f6e9e2399f3179c21c188/04-tools-to-be-successful.md?plain=1#L55

   Replace with:

   ```markdown
   1. **Create a new repository**: Log in to your GitHub account and click the green "New" button on the sidebar. Alternatively, click the "+" icon in the upper right corner and select "New repository" from the dropdown menu. 
   ```

### Steps to reproduce

Open the [Tools to be successful](https://intro.opensauced.pizza/#/04-tools-to-be-successful?id=tools-to-be-successful) chapter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Haimantika** [comment]
@adiati98 can I take this one up?

**Comment by adiati98** [comment]
> @adiati98 can I take this one up?

@Haimantika it's all yours!

**Comment by Haimantika** [comment]
Thanks @adiati98. I have raised the PR.

**Comment by Haimantika** [comment]
@adiati98 sorry for the back and forth. Should be good now.
