### ISSUE TITLE
Feature: Reorganize repo to prepare for Maintainer Course.

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#135]
### Type of feature

🍕 Feature

### Current behavior

Right now, we only have one course here, but soon we'll have two 🎉 We need to reorganize the repo to allow for both courses and remove any unnecessary repetition. For example, we'll only need one COC, not a COC for each course.

### Suggested solution

Following @adiati98's suggestions in: https://github.com/open-sauced/maintainer-intro-course/pull/60 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Can I help with this @BekahHW?

**Comment by BekahHW** [comment]
@CBID2 this is for someone on the docs team.

**Comment by CBID2** [comment]
> @CBID2 this is for someone on the docs team. 

Ok

**Comment by adiati98** [comment]
@BekahHW just a reminder. Every course's folder still need to have their own README, CONTRIBUTING, and i18n Guidelines files.

As CONTRIBUTING and i18n Guidelines have similar content, maybe we can try to combine them together and update the content to accomodate both courses in the Homepage or something.
But a README for every course is a must because it serves as the landing page of each course.

I'll take a look at this when I can make the time.

**Comment by BekahHW** [comment]
@adiati98 yes! I know we definitely need three readmes here.

**Comment by adiati98** [comment]
@BekahHW I'm currently working on this. And I have several questions:

1. We want to have one CONTRIBUTING, i18n Guidelines and Community Translations Guidelines. Should I update the content to accomodate both courses and reflect the future changes in this PR, or wait until we move the maintainer course?

3. We have a link in every chapter to edit the page on GitHub. Do we want to keep this or do we want to use the [docsify-edit-on-github](https://github.com/njleonzhang/docsify-edit-on-github) plugin? If we want to keep the current, we need to adjust the links manually in this PR.

5. We will apply [pagination](https://github.com/imyelo/docsify-pagination#readme) plugin. Is it okay if I apply the plugin from this PR? That way, I can also save time from editing the links manually.

I will hold the rest (styling, etc.) as we only will reorganize the directories structure and update things based on the new structure here.

Thanks! 😊
