### ISSUE TITLE
Feature: Feature: What do I have to fill out on the form to complete step 1?

### ISSUE THREAD

**Issue by alberto-rj** [open-sauced/intro#143]
### Type of feature

📝 Documentation

### Current behavior

I am trying to complete the step 1 by following the instructions in the [**Getting Started**](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started)
section of chapter 5 of the **Intro course**. But unfortunately, I don't know what I should
fill in the form to be able to complete this step successfully.

### Suggested solution

I believe it would be good if there was a clear description of what should be filled
in the form so that other people could complete this first step successfully.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @alberto-rj! :) I was just thinking about this during a conversation in Discord. Do you want to work on this?

**Comment by alberto-rj** [comment]
> Hi @alberto-rj! :) I was just thinking about this during a conversation in Discord. Do you want to work on this?

I can do this if I know what needs to be filled in the form. Do you have any idea what data the user could provide to be able to complete this step in a simple way?

**Comment by CBID2** [comment]
> > Hi @alberto-rj! :) I was just thinking about this during a conversation in Discord. Do you want to work on this?
> 
> I can do this if I know what needs to be filled in the form. Do you have any idea what data the user could provide to be able to complete this step in a simple way?

Data isn’t necessarily needed @alberto-rj for filling out an issue form. It just requires these steps
1. Pick the template that best suits the contribution you want to make. For example, you picked the feature issue form.
2. State the title of the issue: In your case it is “Feature: What do I have to fill out on the form to complete step 1?“ 
3. Describe the problem in the current behavior section
3. Present your solution in the suggested solution section

If you want to keep things simple, it would be “Pick the issue form that best suits your desired contribution & follow the directions described in each section”. Does that make sense?
