### ISSUE TITLE
Feature: What do I have to fill out on the form to complete the step 1?

### ISSUE THREAD

**Issue by alberto-rj** [open-sauced/intro#144]
### Type of feature

🍕 Feature

### Current behavior

I am trying to complete the step 1 by following the instructions in the [**Getting Started**](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started)
section of chapter 5 of the **Intro course**. But unfortunately, I don't know what
I should fill in the form to be able to complete this step successfully.

### Suggested solution

I believe it would be good if there was a clear description of what should be filled
in the form so that other people could complete this first step successfully.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by gs-300** [comment]
Hi @alberto-rj, may I try to solve this issue?

**Comment by alberto-rj** [comment]
> Hi @alberto-rj, may I try to solve this issue?

Yes, @gs-300! You may. But could you tell me your idea?

**Comment by gs-300** [comment]
> > Hi @alberto-rj, may I try to solve this issue?
> 
> Yes, @gs-300! You may. But could you tell me your idea?

sure @alberto-rj, I would add screen shots of each step of the process along with visual markings to show exactly where to click.

**Comment by gs-300** [comment]
> > Hi @alberto-rj, may I try to solve this issue?
> 
> 
> 
> Yes, @gs-300! You may. But could you tell me your idea?

Sorry @alberto-rj, I misunderstood your issue. As I did some further reading it seems that creating a "new issue" is apart of the process in order to sign the guestbook ( which I have not done yet). So I will do so and get back to you if that's ok
