### ISSUE TITLE
Docs: Update the French translation of "Intro to Open Source" course

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#145]
## Description

The English version of our Intro to Open Source course has gone through some updates. But there is no update yet on the French translation for some time.

## Suggested Solution

Update the course's French translation to be synced with the English version. You need to check each page and chapter to update the translation.

Make sure that everything is the same with the English version (headings, spacings, indentations, etc.).

> [!NOTE]
> This issue is suitable for folks who are proficient in French.

**Comment by thomasbnt** [comment]
Hello @adiati98 ! If you need en french translator for the documentation, I can help you! Thanks to @CBID2 for showing me this issue 🙌

**Comment by adiati98** [comment]
Hey @thomasbnt !
Thanks for your interest in helping this out.

It's all yours! 🙌🏼

You can find the translations in the `translations/fr` folder. 

Please let me know if you need any help 😄

**Comment by thomasbnt** [comment]
Ready to review @adiati98 ! :tada:
