### ISSUE TITLE
Docs: Update the "Getting Started" section

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#146]
> [!IMPORTANT]
> If you've worked on a "good first issue" or "beginners only" issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

We added a step to create an issue when contributing to the guestbook repo to encourage participants in creating an issue as part of open source working flow. But this step is often missed. One of the reasons probably because this step is not detail enough for beginners.

## Suggested Solutions

Let's update the wording to create issue as below copy:

```markdown
1. Create an issue by clicking the "Issues" tab on the top bar and then the green "New issue" button. Click the "Get started" button to add contributors, complete the form, and click the "Submit new issue" button.
```

Code to be changed:

https://github.com/open-sauced/intro/blob/58145c60827b4dedec3508928e25bb92c4047d55/docs/intro-to-oss/how-to-contribute-to-open-source.md?plain=1#L142

**Comment by hx4nn** [comment]
hey @adiati98, i'm new here can you assign this to me🙃

**Comment by adiati98** [comment]
@hx4nn it's all you! 👍🏽 

Please read and follow our [Contributing Guidelines](https://intro.opensauced.pizza/#/CONTRIBUTING) before you work on the changes.

**Comment by hx4nn** [comment]
@adiati98, could u pls review changes i did

**Comment by LouisVdwl** [comment]
Hey, can you assign it to me @adiati98 ? ✋
