### ISSUE TITLE
Feature: Add image of profile generated on README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#147]
### Type of feature

🍕 Feature

### Current behavior

We don't have an image to show what kind of screeshot that we expect from contributors.
There are cases where contributors submitted the screenshot of their terminal when running command to add themselves as a contributor. 

### Suggested solution

1. Save below image in your local.

    ![profile-generated-readme](https://github.com/open-sauced/intro/assets/45172775/59563b61-5fa9-4ae6-af4d-9a0cbd33e410)

2. Add the image to `images` folder with the name `profile-generated.png`.
3. Add the image between point 8 and the alert that starts with `!>` in the "[Getting Started](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md#getting-started)" section.
   Give an alt-text of "Profile generated on README".
4. Update the wording in point 8 as follow:

   ```markdown
   8. Copy and paste the Markdown of the README in [Markdown Live Preview](https://markdownlivepreview.com/) and take a screenshot of your profile being generated as the example below. You will need this later when creating a pull request.
   ```

   Code snippet for these changes:

   https://github.com/open-sauced/intro/blob/c3c863688ef04649a2190332db97250867f03137/05-how-to-contribute-to-open-source.md?plain=1#L154-L157

---

> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Jenna59** [comment]
.take
