### ISSUE TITLE
Feature: Add a step to create new branch in the CONTRIBUTING file

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#149]
### Type of feature

📝 Documentation

### Current behavior

We've noticed that some contributors made their changes directly on the `main` branch.

### Suggested solution

We want to make clear that changes are made on new branch and not directly on the `main` branch. 

- [ ] Add step 4 in the "[Setup the Project Locally](https://github.com/open-sauced/intro/blob/main/CONTRIBUTING.md#setup-the-project-locally)" section in the CONTRIBUTING file with copy as follow:

   ````markdown
   4. Create a new branch to work on your changes.

      ```bash
      git checkout -b YOUR-BRANCH-NAME
      ```

      Replace "YOUR-BRANCH-NAME" with a descriptive name for your branch — for example, `feat/add-submit-button`.
   ````

- [ ] Change number 4 to 5.

The code is located here:

https://github.com/open-sauced/intro/blob/c3c863688ef04649a2190332db97250867f03137/CONTRIBUTING.md?plain=1#L33-L39

---

> [!IMPORTANT]
> If you've worked on a good first issue or beginners only issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hx4nn** [comment]
hey @adiati98, I've made a PR could u review it https://github.com/open-sauced/intro/pull/150

**Comment by BekahHW** [comment]
@hx4nn you should be assigned the issue before creating a PR. You can use the `.take` command to self-assign.

**Comment by hx4nn** [comment]
.take

**Comment by adiati98** [comment]
Hey @hx4nn 
You've been assigned to issue #146.

And as stated in the important note on this issue, contributors may only take **one** good first issue.

That been said, I'll unassign you from this issue.

Thanks 😊

**Comment by gs-300** [comment]
.take
