### ISSUE TITLE
Bug: Duplication of the term "Docs" in the Glossary

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#155]
### Describe the bug

> [!IMPORTANT]
> If you've worked on a "beginner only" issue or "good first issue" in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

### Description

There is a duplication of the term "Docs" in our Glossary. Another thing, the example that's given here is not quite accurate.

### Suggested Solution

In the [`10-glossary.md`](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/glossary.md?plain=1) file:

- [ ] Delete the duplication (line 45-48).

   https://github.com/open-sauced/intro/blob/58145c60827b4dedec3508928e25bb92c4047d55/docs/intro-to-oss/glossary.md?plain=1#L45-L48
- [ ] Update the wording in line 23.

   ```markdown
   Docs is an abbreviation for "documentation". It primarily explains how to implement and use a product or an open source project. It also provides information on how to contribute to the project and expectations for contributors. Documentation is often written using [Markdown](https://www.markdownguide.org/), a lightweight markup language.
   ```

   Line to be updated:
   https://github.com/open-sauced/intro/blob/58145c60827b4dedec3508928e25bb92c4047d55/docs/intro-to-oss/glossary.md?plain=1#L23

### Steps to reproduce

1. Go to https://intro.opensauced.pizza/#/intro-to-oss/glossary
2. You will see the duplication of the term "Docs".

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by RishabhDhawad** [comment]
may I proceed with this issue?

**Comment by adiati98** [comment]
@RishabhDhawad it's all yours!
Please let us know if you need any help. Thanks 😊

**Comment by RishabhDhawad** [comment]
Hello Adiati, This time I have created my branch named "rishabh" and tried to raise a PR following the contributing guidelines. If there are still points where I am lacking, do let me know.
