### ISSUE TITLE
Docs: Update the README of Intro to Open Source course

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#156]
> [!IMPORTANT]
> If you've worked on a "beginner only" issue or "good first issue" in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

There are several things that need to be updated on the README based on following reasons:

- There is no link to each chapter in the "Course Overview" section.
- CodeSee is no longer available.
- We've updated the "Types of Contributions" title to "Types of Open Source Contributions".

## Suggested Solution

In the [`README.md` of Intro to Open Source course](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/README.md?plain=1):

- [ ] Provide relative path **to each chapter** in the "Course Overview" section as example below:

   ```markdown
   ### [1. What is Open Source?](what-is-open-source.md)
   ```

- [ ] Omit CodeSee by updating the wording in line 33 as below:

   ```markdown
   Discover the key tools and platforms necessary for a successful journey in open source development. From Git and GitHub for version control and VS Code as your code editor, this chapter provides an overview of how to leverage these essential tools.
   ```

- [ ] Change the title in line 43 as below:

   ```markdown
   ### Types of Open Source Contributions
   ```

---

> [!NOTE]
> Please run the project locally to test the links. They should go to the correct chapters.

**Comment by Muhammad-Rebaal** [comment]
@adiati98 Could you please assign this issue to  me ?

**Comment by adiati98** [comment]
Hey @Muhammad-Rebaal,

You can assign yourself to this issue.
Please read our [Contributing Guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/) for more information.

Thank you. 😊
