### ISSUE TITLE
Bug: favicon isn't the right one

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#158]
> [!IMPORTANT]
> If you've worked on a "good first issue" or "beginners only" issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

### Describe the bug

The favicon for this repo isn't the right one.

You can see here that the correct one is on the left with the one for this course on the right. 
<img width="100" alt="image" src="https://github.com/open-sauced/intro/assets/34313413/73b5457a-2e1d-4c6f-a59f-6d5d96b6e46c">

## Current

The image is currently here: https://github.com/open-sauced/intro/blob/main/docs/_assets/images/pizza-slice.png

## Fix

Let's update the image.
- [ ] Delete https://github.com/open-sauced/intro/blob/main/docs/_assets/images/pizza-slice.png
- [ ] Go to https://opensauced.pizza/press and download "orange slice" as a png
- [ ] In the [/images](https://github.com/open-sauced/intro/blob/main/docs/_assets/images/) folder, add the orange slice png and rename it `pizza-slice.png`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli
