### ISSUE TITLE
Feature: Translate the course to other language

### ISSUE THREAD

**Issue by antonio-pedro99** [open-sauced/intro#16]
### Type of feature

📝 Documentation

### Current behavior

Hi, it is a perfect course for beginners and I would like to introduce it to my newborn open-source community in Angola(github.com/angolaosc), but the biggest part of my community do not speak or understand English. 

### Suggested solution

It would be perfect if we can have a translation of this course.

I will be available to contribute translating most of the part of this course into Portuguese and encourage people from my community to contribute too.

### Additional context

idiom

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I'd love to see this course get translated. I used to run workshops when I worked at GitHub and the platform is able to handle translations based on the language set by the browser using the language codes in the README. 

For example the pattern would be the following
1. create the folder for the language i.e. `portugese-brasil` 
2. suffix `pt-br` to the files. 

see the example here in Korean. cc @BekahHW 

https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.ko.md

also pt-br

https://github.com/github-craftwork/python-brasil/blob/master/README-pt-br.md

**Comment by CBID2** [comment]
I like this idea too @bdougie. Let me see if I can figure something out.

**Comment by antonio-pedro99** [comment]
@bdougie nice you liked the idea. 
@CBID2 is planning to open a PR for that, I am in to contribute with the Portuguese translation

**Comment by CBID2** [comment]
> @bdougie nice you liked the idea. 
> 
> @CBID2 is planning to open a PR for that, I am in to contribute with the Portuguese translation 

If I get the ok from @BekahHW of course

**Comment by antonio-pedro99** [comment]
> > @bdougie nice you liked the idea.
> > @CBID2 is planning to open a PR for that, I am in to contribute with the Portuguese translation
> 
> If I get the ok from @BekahHW of course

LGTM

**Comment by BekahHW** [comment]
@CBID2 Sounds great!

**Comment by antonio-pedro99** [comment]
> @CBID2 Sounds great!

👌👌👌

**Comment by antonio-pedro99** [comment]
@CBID2 what's on your mind for the first PR?

**Comment by CBID2** [comment]
> @CBID2 what's on your mind for the first PR?

Good question @antonio-pedro99. I'm thinking of this:
1. Creating the file structure for the bilingual Markdown files 
2. Create a Draft PR, so you can add the Portuguese version of the files
How does that sound?

**Comment by antonio-pedro99** [comment]
@CBID2 We need to think how to organize the repo to be able to support multiples languages. If we just translate page by page each .md file in the root, we will have lot of files and the navigation through the repository will be hard.

I am not sure docsify supports it, but my initial thought is to create a folder for each translation. Something like

pt-br/
.... 01-Introduçāo.md
.... 02-Outra Sessão.md
....
.... 09-Glossário.md 


What do you think?

**Comment by antonio-pedro99** [comment]
> > @CBID2 what's on your mind for the first PR?
> 
> Good question @antonio-pedro99. I'm thinking of this:
> 
> 1. Creating the file structure for the bilingual Markdown files based on the links @bdougie provided.
> 2. Create a Draft PR, so you can add the Portuguese version of the files
>    How does that sound?

Wait, do you speak Portuguese? Hahahha

**Comment by antonio-pedro99** [comment]
I like the idea. 
It is cery

> > @CBID2 what's on your mind for the first PR?
> 
> Good question @antonio-pedro99. I'm thinking of this:
> 
> 1. Creating the file structure for the bilingual Markdown files based on the links @bdougie provided.
> 2. Create a Draft PR, so you can add the Portuguese version of the files
>    How does that sound?

Yes, it is very similar to what I wrote recently

**Comment by CBID2** [comment]
> @CBID2 We need to think how to organize the repo to be able to support multiples languages. If we just translate page by page each .md file in the root, we will have lot of files and the navigation through the repository will be hard.
> 
> 
> 
> I am not sure docsify supports it, but my initial thought is to create a folder for each translation. Something like
> 
> 
> 
> pt-br/
> 
> .... 01-Introduçāo.md
> 
> .... 02-Outra Sessão.md
> 
> ....
> 
> .... 09-Glossário.md 
> 
> 
> 
> 
> 
> What do you think?

I like that

**Comment by CBID2** [comment]
I'm going to start the draft PR tomorrow if you don't mind @antonio-pedro99

**Comment by antonio-pedro99** [comment]
Please take your time

**Comment by CBID2** [comment]
> Please take your time

Hey @antonio-pedro99! :) I started the pull request for this issue. I placed it in draft mode so you can start adding the translated files.

**Comment by antonio-pedro99** [comment]
> > Please take your time
> 
> Hey @antonio-pedro99! :) I started the pull request for this issue. I placed it in draft mode so you can start adding the translated files.

Hi @CBID2, thanks for that. I am on it.

**Comment by antonio-pedro99** [comment]
@bdougie @CBID2 @BekahHW should we create a milestone for this issue? We are not going to translate to Portuguese only. 
Tell me what you think.

**Comment by CBID2** [comment]
> @bdougie @CBID2 @BekahHW should we create a milestone for this issue? We are not going to translate to Portuguese only. 
> 
> Tell me what you think.

I agree @antonio-pedro99. It's a significant thing

**Comment by geoffreylgv** [comment]
Hi @CBID2 @bdougie @BekahHW @antonio-pedro99 
I would like to contribute to the intro to open source in French version.

Since the translation folder is in draft, can I do it, 
or a maintainer should create fr-fr folder for me, 
or I will wait for the PR+merge, to start ?

**Comment by antonio-pedro99** [comment]
> Hi @CBID2 @bdougie @BekahHW @antonio-pedro99 I would like to contribute to the intro to open source in French version.
> 
> Since the translation folder is in draft, can I do it, or a maintainer should create fr-fr folder for me, or I will wait for the PR+merge, to start ?

Hey @geoffreylgv, sounds interesting. 
I am fine with that. 

Let's wait what others will say.

**Comment by CBID2** [comment]
> Hi @CBID2 @bdougie @BekahHW @antonio-pedro99 
> 
> I would like to contribute to the intro to open source in French version.
> 
> 
> 
> Since the translation folder is in draft, can I do it, 
> 
> or a maintainer should create fr-fr folder for me, 
> 
> or I will wait for the PR+merge, to start ?

I was just about to do it in French too @geoffreylgv. 😊 I'll set up the folders and files. From there, you can translate the rest.

**Comment by geoffreylgv** [comment]
Ok perfect, thank you

**Comment by CBID2** [comment]
> Ok perfect, thank you

Hey @geoffreylgv! :) I just sent you an invite to my fork, check your email

**Comment by CBID2** [comment]
Hey @antonio-pedro99. Here's the PR for the sidebar @geoffreylgv made: https://github.com/open-sauced/intro/pull/42
