### ISSUE TITLE
Feature: Add a link to the "Job Seekers Guide"

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#175]
### Current behavior

> [!IMPORTANT]
> If you've worked on a "beginner only" issue or "good first issue" in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

We have a "Job Seekers Guide" in our docs that is suitable to be added into the "Intro to Open Source" course.

### Suggested solution

In line 75 in the [`docs/intro-to-oss/the-secret-sauce.md`](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/the-secret-sauce.md), add a sentence at the end with copy as follow:

```markdown
Additionally, you can refer to the [Job Seekers Guide](https://docs.opensauced.pizza/opensauced-guides/job-seekers-guide/job-seekers-guide-introduction/) on our docs to learn how to use OpenSauced to land a job in the tech industry.
```

Code to be improved:

https://github.com/open-sauced/intro/blob/5476877fcc352429459a28c6a2f72083a78ff095/docs/intro-to-oss/the-secret-sauce.md?plain=1#L75

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by smhussain5** [comment]
.take

I've only worked on one good-first-issue before, I'm wondering if this is a hard-limit. If so, I'm happy to let someone else take it; otherwise, I'm happy to work on this!

**Comment by adiati98** [comment]
@smhussain5 unfortunately, yes. It's a hard limit. That said, I'll unassign you from this issue.
Thank you for your understanding!

**Comment by NeilGeorge1** [comment]
Hello!! First timer here! Could you assign me this issue?
