### ISSUE TITLE
fix: Add information on the PR process for contributing

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#176]
## Context

After walking a contributor though their first contribution on another repo, it made it clear that we could support them by creating clearer directions for submitting a PR. 

## Suggestions

It's important to note that all projects will differ in what their requirements are, but many projects will require you to:

1. Complete a PR template
2. Check your work by running it locally

For 1. it can be tricky for a contributor to understand what they're seeing. I think it's worth doing a side-by-side shot of what a PR template looks like in raw md. format v. rendered md format. 

Contributors should include a description, learn about [using keywords in a PR](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), and provide any other necessary information. 

For 2. we should explain where to find the direction for running a project locally and explain why it's important to do that before submitting a PR for review.

**Comment by CBID2** [comment]
I can work on this @BekahHW

**Comment by BekahHW** [comment]
@CBID2 let's make sure your other PR gets merged in first and if this is still available, I'll assign you.
