### ISSUE TITLE
Feature:

### ISSUE THREAD

**Issue by madefromjames** [open-sauced/intro#177]
### Current behavior

As part of the Intro to Open Source course, I am encouraged to contribute to this repo.

### Suggested solution

Add myself as a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@madefromjames wrong repo?

**Comment by madefromjames** [comment]
> @madefromjames wrong repo?

It's not a wrong repo. I was following the instructions on `how-to-contribute-to-open-source.md` Please let me know if I'm on the right path.
<img width="644" alt="image" src="https://github.com/open-sauced/intro/assets/104380115/f0860396-4ae7-4124-9c44-f2cdab35e2e0">

**Comment by madefromjames** [comment]
Hi @adiati98  I did something completely different by creating an issue for my personal work, I figured out it was supposed to be an issue for the guestbook repo, and I later edited the previous content. I'm learning and knowing what to do right as I'm learning further, I'm also yet to get my work merged for the guestbook repo and pizza-verse repo. Thanks for your response.

**Comment by adiati98** [comment]
@madefromjames, you then need to create the issue in the guestbook repo. I've left a comment in your PR on that repo.

Please let me know if you have questions or need any help. 😊

**Comment by madefromjames** [comment]
> @madefromjames, you then need to create the issue in the guestbook repo. I've left a comment in your PR on that repo.
> 
> Please let me know if you have questions or need any help. 😊

Okay one thing I also need to understand is that is it optional to create an issue if I need to PR. Do I need an issue for PR. I'm also wondering if they work together.

**Comment by adiati98** [comment]
> Okay one thing I also need to understand is that is it optional to create an issue if I need to PR. Do I need an issue for PR.

In most open source projects (if not all), having an issue to accompany a PR is a must. So, you need to either working on an open issue or creating a new issue before working on changes and making a PR.

There are several reasons why you need to have an issue with a PR, which are to ensure:

- there is no duplication.
- the proposed changes in the issue is align with the project's goal.

Working on changes directly and creating a PR without an issue will most likely result in your PR being rejected if it does not align with the project's needs or is not a priority.

I hope these anwer your questions. 🙂 

> I'm also wondering if they work together.

I'm not sure if I understand what you mean here. Would you please explain what you mean?

**Comment by madefromjames** [comment]
> > Okay one thing I also need to understand is that is it optional to create an issue if I need to PR. Do I need an issue for PR.
> 
> In most open source projects (if not all), having an issue to accompany a PR is a must. So, you need to either working on an open issue or creating a new issue before working on changes and making a PR.
> 
> There are several reasons why you need to have an issue with a PR, which are to ensure:
> 
> * there is no duplication.
> * the proposed changes in the issue is align with the project's goal.
> 
> Working on changes directly and creating a PR without an issue will most likely result in your PR being rejected if it does not align with the project's needs or is not a priority.
> 
> I hope these anwer your questions. 🙂
> 
> > I'm also wondering if they work together.
> 
> I'm not sure if I understand what you mean here. Would you please explain what you mean?

Thank you @adiati98 I appreciate the time and effort in making me have a good understanding of issues for PR. I'm ready to continue and contribute to more open-source projects. You can also check the pizza-verse repo for the changes I made in the PR. 😚
