### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by madefromjames** [open-sauced/intro#178]
### Describe the bug

As part of the Intro to Open Source course, I am encouraged to contribute to this repo.

### Steps to reproduce

Adding myself as a contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
Hi @madefromjames,

I believe you're creating issue for our [guestbook repo](https://github.com/open-sauced/guestbook). 😊 

That said, I'm closing this issue.

**Comment by adiati98** [comment]
Hi @madefromjames,
Would you please let us know what do you find difficult to follow?

We need to first review your PR before we can merge it in. Please be patience. We definitely will get to it. 😊

**Comment by madefromjames** [comment]
Thanks for your response @adiati98 It was my first getting to use `issues` on Github and I didn't know what issues to create or what contributors I need to add but I was able to view other people's past issue to have an idea on what to do.
