### ISSUE TITLE
Feature: add OpenSauced logo on dark, in the French Sidebar

### ISSUE THREAD

**Issue by samucodesh** [open-sauced/intro#183]
### Suggested solution

![Screenshot 2024-05-07 14 33 23](https://github.com/open-sauced/intro/assets/108969323/25e9ffaa-c891-402f-8346-40a01f5641c5)

## Suggested solution

`[![OpenSauced Logo](../../../_assets/images/logo-on-dark.png)](https://opensauced.pizza/)`

**Comment by adiati98** [comment]
Thanks for reporting this, @samucodesh!
Do you want to work on this?

**Comment by samucodesh** [comment]
@adiati98  Yes, I am eager to contribute.

**Comment by adiati98** [comment]
@samucodesh It's all you!
