### ISSUE TITLE
Bug:  us navbar: relative paths

### ISSUE THREAD

**Issue by samucodesh** [open-sauced/intro#184]
### Describe the bug

when navigating to a language from the navbar it returns 404 not found

### Steps to reproduce

1. navigate to the following path: intro/docs/intro-to-oss/_navbar.md and choose one of the language options

## solution?

```
  - [:us: English](../intro-to-oss/)
  - [:fr: French](../intro-to-oss/translations/fr/)
```

**Comment by adiati98** [comment]
Hi @samucodesh,

Thank you for reporting the issue!

However, we only use the navbar for the website. And there, I can navigate to each language (English & French) without any problem as below screen recording.

Can you provide screenshot or screen recording to show the bug? Thanks!

https://github.com/open-sauced/intro/assets/45172775/cd251ef0-cf7b-4b66-8a09-1ee0f40c3f82
