### ISSUE TITLE
Typographical error in English version

### ISSUE THREAD

**Issue by idrista** [open-sauced/intro#189]
### Discussed in https://github.com/open-sauced/intro/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **idrista** May  2, 2024</sup>
In the "Prerequisites" section, I believe I've spotted a typographical error. Is it intentional?
« starting> this course » 

https://github.com/open-sauced/intro/blob/4b63c8022206374b0aadd73d694ac7e9e53dabef/docs/intro-to-oss/intro.md?plain=1#L9</div>

Further to @adiati98 feedback , here's the issue to rectify this typo

**Comment by adiati98** [comment]
Hi @idrista,

Thank you for the issue! ✨ 
However, can you please use the "bug" issue form to report the issue so we can understand it better?

Thank you in advance!

**Comment by idrista** [comment]
Done, this issue will be replaced by https://github.com/open-sauced/intro/issues/192
