### ISSUE TITLE
Bug: Typographical error in English version

### ISSUE THREAD

**Issue by idrista** [open-sauced/intro#192]
### Describe the bug

I found a typo, as discussed at https://github.com/open-sauced/intro/discussions/179

In the intro.md (English version), there's an unexpected '>' at the end of the line `starting> this course`

https://github.com/open-sauced/intro/blob/6e5f0615fb73565569dfc18339ab633f215c014f/docs/intro-to-oss/intro.md?plain=1#L9

### Steps to reproduce

Check into intro.md (line 9)
https://github.com/open-sauced/intro/blob/6e5f0615fb73565569dfc18339ab633f215c014f/docs/intro-to-oss/intro.md?plain=1#L9

**Comment by adiati98** [comment]
Thank you for reporting this, @idrista! ✨

**Comment by georgepence** [comment]
.take
