### ISSUE TITLE
Feature: Mention template option in "Setting up a Code of Conduct file" chapter of Maintainer's Course 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#195]
### Suggested solution

According to GitHub's documentation, [there are templates provided for the Code of Conduct file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template). 
It would be helpful to add this information as a note in this section so that maintainers who want a quicker way to set up this file.

**Comment by BekahHW** [comment]
Oh nice! I didn't know about that. Seems like a good addition.

**Comment by CBID2** [comment]
Great! Can I add that @BekahHW?

**Comment by CBID2** [comment]
Hi @BekahHW. Since you gave a thumbs up emoji for my question, I created a PR for the issue. It's #202.
