### ISSUE TITLE
Feature: Adding a chapter about Security to Becoming a Maintainer Course 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#196]
### Suggested solution

Since security policies is one of the elements to a [healthy repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) and [84% of open source codebases have security vulnerabilities](https://www.synopsys.com/software-integrity/resources/analyst-reports/open-source-security-risk-analysis.html?utm_source=google&utm_medium=cpc&utm_term=open_source_security&utm_campaign=G_S_OSSRA_BMM&cmp=ps-SIG-G_S_OSSRA_BMM&gad_source=1&gclid=Cj0KCQjw3ZayBhDRARIsAPWzx8o4YVulBXoY1ZaTxztIOXm1Jr1zBCGrpsAOONc9ImrQeqS_kdYN3wAaAmVxEALw_wcB) it would be helpful to add a chapter on this topic so that maintainers can be prepared when facing these kinds of issues.

**Comment by adiati98** [comment]
Hey @CBID2,

Would [this section](https://intro.opensauced.pizza/#/becoming-a-maintainer/issues-and-pull-requests?id=security-vulnerabilities-handling) answering your issue here?

**Comment by CBID2** [comment]
> Hey @CBID2,
> 
> 
> 
> Would [this section](https://intro.opensauced.pizza/#/becoming-a-maintainer/issues-and-pull-requests?id=security-vulnerabilities-handling) answering your issue here?

Ahh ok thanks @adiati98
