### ISSUE TITLE
Bug: Broken link in the Guestbooks chapter in "Becoming a Maintainer" course

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#197]
### Describe the bug

When clicking on link to the Project's list in the Maintainers Guestbook chapter, nothing appears. 

### Steps to reproduce

1. Go to Maintainers Guestbook in the navigation tab
2. Go to [Projects List link](https://intro.opensauced.pizza/#/becoming-a-maintainer/maintainers-guestbook?id=projects-list)
3. Click on the link to the Projects list 

### Video of tutorial

https://github.com/open-sauced/intro/assets/105683440/2721c07c-967e-4863-ba8c-1dc6adb67791

**Comment by adiati98** [comment]
Hi @CBID2,

Thank you for the issue! ✨ 

The "Projects List" here is a title for the future projects that new contributors would like to share. So, it's not a link to any other page.🙂
You can see the [raw code](https://github.com/open-sauced/intro/blob/main/docs/becoming-a-maintainer/maintainers-guestbook.md?plain=1) to understand it better.

That said, I'm closing this issue.
