### ISSUE TITLE
Bug: no padding between icon and text

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/intro#20]
### Describe the bug

There is no padding between the icon and text on mobile view
![Screenshot_20230724-210809](https://github.com/open-sauced/intro/assets/72051159/d7d76c1a-1220-4b38-bdb8-756ddddb13d8)

### Steps to reproduce

1. Go to https://intro.opensauced.pizza/#/01-intro
2. See error 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Suldana** [comment]
@dev-phantom I'm interested in solving this issue please assign to me

**Comment by dev-phantom** [comment]
> @dev-phantom I'm interested in solving this issue please assign to me

Nice😊

You can use the `.take` to self assign your self to the issue

**Comment by Muniir1** [comment]
.take

**Comment by munniomer** [comment]
`.take`

**Comment by Muniir1** [comment]
`.take`

**Comment by Muniir1** [comment]
.take

**Comment by luqman-salad** [comment]
.take

**Comment by Suldana** [comment]
.take

**Comment by dev-phantom** [comment]
@OgDev-01 please can you assign @Suldana  to this

**Comment by Muniir1** [comment]
@OgDev-01  Please assign me i have fixed the issue

**Comment by Suldana** [comment]
dear @OgDev-01 please assign this issue to @Muniir1 he worked hard to solve this issue, please assign to him, thanks

**Comment by dev-phantom** [comment]
I'm confused here sorry
I thought @Suldana had already fix this issue?

**Comment by Ganesh1521** [comment]
Here is Code to fix this problem

.content {
    display: flex;
    align-items: center; 
    padding: 20px; 
}


.text {
    flex: 1; 
    padding-right: 20px;
}


.diagram {
    flex: 1; 
    text-align: center; 
}


.diagram img {
    max-width: 100%; 
}

**Comment by CBID2** [comment]
> Here is Code to fix this problem
> 
> .content { display: flex; align-items: center; padding: 20px; }
> 
> .text { flex: 1; padding-right: 20px; }
> 
> .diagram { flex: 1; text-align: center; }
> 
> .diagram img { max-width: 100%; }

Thanks @Ganesh1521, but PR #27, solves this.
