### ISSUE TITLE
Feature: Move `CONTRIBUTING.md` and `i18n-guidelines.md` to the root

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#206]
## Background

As I'm trying to find a way to create a base for our community translations, it gave me a thought.

So far, I don't see any open source project that has contributing & translation guidelines chapters on their live website. Usually, they have either:

   - "Edit this page on GH" that bring folks to the page file on GH, or
   - Link to the repo on GH.

   But we do have [contributing guidelines](https://intro.opensauced.pizza/#/CONTRIBUTING) and [translations guidelines](http://localhost:3000/#/i18n-guidelines) live on our website. I think it makes more sense if these files live _only_ in the repo.

For that reason, I propose to move `CONTRIBUTING.md` and `i18n-guidelines.md` to the root. We will still link these on the homepage of the course.

### Alternative

If we want to be a bit more organized, we can follow GH docs repo. They have a [contributing folder](https://github.com/github/docs/tree/main/contributing) that contains various contributing guidelines. So we can create a `contributing` folder at the root and move the guidelines files into this folder.

## Community Translations

In the forked repo of translations, they will have these in their root:

- Translated `CONTRIBUTING.md`.
- Translated `i18n-guidelines.md`.
- A contributing file that contains guidelines to contribute to the forked repo.

   They can name it anything, but preferably consistent across forked repos for documentation matter. So, maybe something like: `CONTRIBUTING-TO-LANG.md` and change the `LANG` to the translated languange. For example: `CONTRIBUTING-TO-ES.md`. They can link this file in the README on the root. This file can be upper- or lower-case. It doesn't matter as there is no convention for this. However, we want this to be consistent across forked repos.

**Comment by adiati98** [comment]
@BekahHW I need your thoughts and want to discuss this further with you whenever you have time. Thanks! 🙂

**Comment by adiati98** [comment]
@BekahHW I'm considering to remove the "Contributing to This Repository" and "License" sections from both courses' README (as screenshot below) and leave those only in the homepage.

![Screenshot 2024-05-31 181848](https://github.com/open-sauced/intro/assets/45172775/d7db2459-eb63-4644-979b-8e4bd4e5e3f2)


I looked at open source projects, some of them don't mention about contrib guidelines on their websites (e.g., [Astro](https://docs.astro.build/en/getting-started/), [React](https://docs.astro.build/en/getting-started/)), and some have a dedicated page for contrib guidelines (e.g., [NextJS](https://nextjs.org/docs/community/contribution-guide) — navigate from the sidebar under "Community", [GH Docs](https://docs.github.com/en) — listed on the homepage under "Community"). 

Any thoughts?

**Comment by BekahHW** [comment]
> @BekahHW I'm considering to remove the "Contributing to This Repository" and "License" sections from both courses' README (as screenshot below) and leave those only in the homepage.
> 
> ![Screenshot 2024-05-31 181848](https://private-user-images.githubusercontent.com/45172775/335656608-d7db2459-eb63-4644-979b-8e4bd4e5e3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDM3NTEsIm5iZiI6MTcxNzQ0MzQ1MSwicGF0aCI6Ii80NTE3Mjc3NS8zMzU2NTY2MDgtZDdkYjI0NTktZWI2My00NjQ0LTk3OWItOGU0YmQ0ZTVlM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE5MzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDg1YzgzMDBiMmM5NzQzODMwOTI2YTc1MDFlY2Q4Y2VhMjQwMmZiOGVmOTcyZjQ1OTdjM2Q1MmM2YTBjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AE3Vl5LtiUHHtbYhCdGlev6LGG9EeWa0Lvj2pdjq52c)
> 
> I looked at open source projects, some of them don't mention about contrib guidelines on their websites (e.g., [Astro](https://docs.astro.build/en/getting-started/), [React](https://docs.astro.build/en/getting-started/)), and some have a dedicated page for contrib guidelines (e.g., [NextJS](https://nextjs.org/docs/community/contribution-guide) — navigate from the sidebar under "Community", [GH Docs](https://docs.github.com/en) — listed on the homepage under "Community").
> 
> Any thoughts?

License can definitely go in one place. If the contrib guidelines are the same for both, it makes sense to keep them in one place as well.
