### ISSUE TITLE
Feature: Add Arabic translation 

### ISSUE THREAD

**Issue by dvmhmdsd** [open-sauced/intro#211]
### Suggested solution

Hi, I would like to make this guide more accessible to Arabic-speaking developers and users by translating the documentation and other relevant materials into **Arabic**. This will help this guide to reach a wider audience and ensure that more people can benefit from this awesome work.

I'm ready to translate the project into **Arabic** and get other contributors for this mission.

**Comment by adiati98** [comment]
Hey @dvmhmdsd,

Thank you for your interest in translating our courses!

Please read our [translation guidelines](https://intro.opensauced.pizza/#/i18n-guidelines?id=%f0%9f%8c%90-i18n-guidelines), particularly the [Community Translations](https://intro.opensauced.pizza/#/i18n-guidelines?id=_2-community-translations) section.

Let us know if you have any question or help! ✨

**Comment by adiati98** [comment]
Hi @dvmhmdsd 

We can't always support the maintenance of translations. 

Have you read the [Community Translation](https://intro.opensauced.pizza/#/i18n-guidelines?id=_2-community-translations) that I've linked before? 

There, you can see:

> If you're interested in translating our Intro to Open Source course, fork this repository and add the translation to your forked repository.

That said, you need to maintain this forked repository yourself, look for contributors who can help you to translate, and host the translations yourself. 

You don't need to create a PR in this repo, but do list your translations repository in the `community-translations.md` file. 🙂

Please let me know if you have any questions.

**Comment by dvmhmdsd** [comment]
> Hi @dvmhmdsd 
> 
> We can't always support the maintenance of translations. 
> 
> Have you read the [Community Translation](https://intro.opensauced.pizza/#/i18n-guidelines?id=_2-community-translations) that I've linked before? 
> 
> There, you can see:
> 
> > If you're interested in translating our Intro to Open Source course, fork this repository and add the translation to your forked repository.
> 
> That said, you need to maintain this forked repository yourself, look for contributors who can help you to translate, and host the translations yourself. 
> 
> You don't need to create a PR in this repo, but do list your translations repository in the `community-translations.md` file. 🙂
> 
> Please let me know if you have any questions. 

So, I shouldn't make a PR for the translation and just put the link of the forked repo into the `community-translations.md` file?

When we finish the translation, how will the users reach the translation through your website? Or should I deploy it myself?

**Comment by adiati98** [comment]
> So, I shouldn't make a PR for the translation and just put the link of the forked repo into the `community-translations.md` file?

Yes. You can put the link of the forked repo into the file. And that's how users can reach the translations. 🙂 
 
> When we finish the translation, how will the users reach the translation through your website? Or should I deploy it myself?

As I mentioned before, you need to host (deploy) the website of the translations yourself.

I suggest you follow [this discussion](https://github.com/open-sauced/intro/discussions/190). The Spanish translations is now working on theirs. 😊
