### ISSUE TITLE
Feature: Remove `.DS_STORE` File and Ignore in `.gitignore`

### ISSUE THREAD

**Issue by samucodesh** [open-sauced/intro#224]
### Suggested solution

The `.DS_STORE` files are generated by macOS and are not needed in the repository. 

1. **Delete existing `.DS_STORE` file** 

2. **Add `.DS_STORE` to `.gitignore`:** 
   -  Add the following line to the `.gitignore` file: `*.DS_STORE`
   
This will prevent future `.DS_STORE` files from being added to the repository, keeping it clean and efficient.

**Comment by samucodesh** [comment]
Hello @adiati98 

If possible, I would like to work on it.

Also, i think it's a good idea to add: `.idx/`, `.devcontainer/` and `.vscode/` to the `.gitignore` file to prevent it from being added to the repository by mistake.

**Comment by BekahHW** [comment]
@samucodesh I'm sorry to have missed this. Is this something you're still interested in working on?

**Comment by samucodesh** [comment]
> @samucodesh I'm sorry to have missed this. Is this something you're still interested in working on?

Absolutely, I'm still very interested in working on this.

**Comment by adiati98** [comment]
@samucodesh you can now claim it. 🙂

**Comment by samucodesh** [comment]
.take
