### ISSUE TITLE
Bug : Broken "Edit the Page" Link on Intro to OSS Page

### ISSUE THREAD

**Issue by Codexnever** [open-sauced/intro#241]
### Expected Behavior
The link should redirect to the correct file for editing in the repository, allowing users to contribute to the documentation.

### Actual Behavior
The link leads to a 404 Not Found error, preventing access to the intended editing page.

### Steps to reproduce

![bug](https://github.com/user-attachments/assets/637563e2-50c9-4f1b-bafe-8b13c415e17d)
---
### Steps to Reproduce
1. Go to the [Intro to Open Source Course](https://opensauced.pizza/learn/intro-to-oss/).
2. Scroll down to the bottom of the page.
3. Click on the "Edit the page" link.
4. Observe that it redirects to [https://github.com/open-sauced/intro/docs/intro-to-oss/README.md](https://github.com/open-sauced/intro/docs/intro-to-oss/README.md), which results in a 404 error.

---
I would like to be assigned to this issue to help resolve it. Thank you!

**Comment by adiati98** [comment]
Hey @Codexnever,

We've removed the `needs triage` label. You can assign yourself to this issue.
Please read our [Contributing Guidelines](https://github.com/open-sauced/intro/blob/main/contributing/CONTRIBUTING.md) for more information.

Thank you. 😊

**Comment by Codexnever** [comment]
.take

Thank you for removing the label, @adiati98  I'll start working on the issue now. 😊

**Comment by Codexnever** [comment]
Hey @adiati98 ,

I need some assistance regarding my recent changes in open-sauced/intro project. 

### Background:
I made some changes in the Docusaurus files, specifically in the `site-docs-intro-to-oss-readme-md-014.json` file located at:
```
.docusaurus/docusaurus-plugin-content-docs/default/site-docs-intro-to-oss-readme-md-014.json
```
The changes work perfectly on my local environment, but when I try to push them, I encounter issues during the deploy preview.

### The Issue:
I noticed that my Docusaurus site is not loading properly in the preview. A common error I see is:
```
Your Docusaurus site did not load properly.
A very common reason is a wrong site baseUrl configuration.
Current configured baseUrl = /learn/
We suggest trying baseUrl = /
```

### Git Configuration:
Currently, my `.gitignore` file includes the following lines regarding the Docusaurus folder:
```
!.docusaurus/docusaurus-plugin-content-docs/default/site-docs-intro-to-oss-readme-md-014.json
.docusaurus/
```
I want to know if it’s advisable to remove the Docusaurus folder from the `.gitignore` file altogether to push all changes or if I should only be focusing on the specific file I modified.
![Deploy err](https://github.com/user-attachments/assets/80961576-de41-40ee-88f1-f831cbbf1f6b)

### Questions:
1. **Should I remove `.docusaurus/` from my `.gitignore` to push all changes related to Docusaurus?**
2. **Is there a specific reason why the site works locally but fails in the preview?**
3. **Are there any best practices or guidelines for handling generated files in Docusaurus that I should be aware of?**

**Comment by BekahHW** [comment]
@Codexnever you shouldn't need to make any changes in your docusaurus files. 

So the reason it works locally and not on the preview is bc it's working from a redirected site. You can create the PR if it's working locally.

**Comment by Codexnever** [comment]
Hey @BekahHW ,

I noticed that while everything works fine locally, the deploy preview is showing an issue with the baseUrl configuration. The error message states:

"Your Docusaurus site did not load properly. A very common reason is a wrong site baseUrl configuration. Current configured baseUrl = /learn/."

It suggests trying baseUrl = /, but my config has it set to /learn/ as needed. When I go to the /learn route manually, it works fine, but initially, this error appears. Additionally, the deploy preview isn't loading the CSS properly, so only text-based content is displayed.

I’ve raised a PR which you can check #247  , but this issue seems to persist only in the deployment. Could you take a look and let me know if there are any adjustments I should make or if there's something with the deployment setup causing the issue?
