### ISSUE TITLE
Bug: Misaligned Buttons in Course Cards on the Homepage Due to Varying Content Length

### ISSUE THREAD

**Issue by Codexnever** [open-sauced/intro#243]
### Describe the bug

The buttons "Start the Intro to Open Source Course" and "Start the Becoming a Maintainer Course" are misaligned in the card components. The button in the "Becoming a Maintainer" card appears higher than the button in the "Intro to Open Source Course" card due to differences in the content length of the two cards. This creates an inconsistent user experience and disrupts the visual layout of the page.
![Before](https://github.com/user-attachments/assets/3e34b3f3-f8c5-48da-8963-c257f58e6a12)

### Steps to reproduce

1. Navigate to the page that displays both the "Intro to Open Source Course" and "Becoming a Maintainer Course" cards.
2. Observe that the "Becoming a Maintainer" card has less content compared to the "Intro to Open Source Course" card.
3. Notice that the button for "Start the Becoming a Maintainer Course" is positioned higher than the button for "Start the Intro to Open Source Course."
4. The misalignment becomes more evident on varying screen sizes.

**Comment by adiati98** [comment]
Hey @Codexnever,
I've removed the `needs-triage` label. You can assign yourself to this issue if you'd like to work on it. 👍🏼

**Comment by Codexnever** [comment]
.take
