### ISSUE TITLE
Feature: Add image of completed PR template for Guestbook

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#244]
### Suggested solution

One of the things we see a lot when reviewing the guestbook PRs is the PR form isn't filled out properly. 

In the [Getting Started Section of the Practical Application](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#getting-started) let's add a screenshot below the warning after the text of 11.

Here's what a completed Pull Request Template for the guestbook looks like. Make sure yours looks like this, with your unique information.

<img width="689" alt="image" src="https://github.com/user-attachments/assets/a06fa32c-40c9-4e02-84cc-9e9d5350aaa7">

**Comment by pedaars** [comment]
@BekahHW happy to pick this issue up

**Comment by BekahHW** [comment]
Thanks! @pedaars please take a look at our [contributing guidelines](https://github.com/open-sauced/intro/blob/main/contributing/CONTRIBUTING.md) to assign yourself the issue.
