### ISSUE TITLE
Feature: Forking feature can be added in documentation for learners.

### ISSUE THREAD

**Issue by rishita-badole** [open-sauced/intro#248]
### Suggested solution

I would also suggest including in the documentation that while creating a new repository is recommended for open source contributions, forking the repository can remain an option as well. This approach offers flexibility for contributors and encourages collaboration. Also I think the documentation could be left open to contribute for better suggestions.

**Comment by adiati98** [comment]
Hi @rishita-badole,
Thank you for raising this issue. ✨ 

I'm not sure I understand what you mean by this sentence below. Can you please elaborate?

> while creating a new repository is recommended for open source contributions, forking the repository can remain an option as well. 

And responding to this one:

> Also I think the documentation could be left open to contribute for better suggestions.

Our repository is always open for contributions. 🙂 

To add information based on your comment on issue #240, most of issues in this repo are meant to be worked on by contributors, but high priority issues are for our docs team to work on.
