### ISSUE TITLE
Bug: Database connection Issue

### ISSUE THREAD

**Issue by Obasoro** [open-sauced/intro#29]
### Describe the bug
```Could not ping database: dial tcp [::1]:9999: connect: connection refused```

**Comment by dev-phantom** [comment]
Please give your issue a descriptive name. This helps contributors get a glance at what they need to fix.

**Comment by Obasoro** [comment]
Thanks @dev-phantom. ``` Database connection Issue ```

**Comment by dev-phantom** [comment]
> Thanks @dev-phantom. `Database connection Issue`

Nope make it the PR title
e.g (Bug: Database connection Issue)

**Comment by BekahHW** [comment]
@Obasoro I'm closing this issue because there aren't any details filled out in the bug report. If you're still having a problem, please fill out the full bug report form.

**Comment by Obasoro** [comment]
Thank you, A response on how to go about this error has been shared on the discord by @bdougie
