### ISSUE TITLE
Feature: Revise certain parts

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#30]
### Type of feature

📝 Documentation

### Current behavior

I was reading [through Chapter 6](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md) of the intro course, and I noticed that Step 4 and the next paragraph seem to repetitive:

"Once this is done, we are ready to share our profile with the world! Click the share button in the top right portion of your profile page to get a link to your profile. You can share this link with others to showcase your open source contributions."

Share it!: Once you've built up a portfolio of open source contributions, you can share your OpenSauced resume with others by clicking the share button in the header of your profile page. This can be especially helpful when applying for jobs, networking with other developers, or promoting your work in the open source community."

### Suggested solution

To improve this section, I suggest removing the statement that starts with "Once this is done" and use Step 4 only:

Formatting your Highlight
To be most effective in highlighting your contributions, we recommend using the following format:

Title: This should be a short description of the contribution. For example, "Created a GitHub Action to automatically merge pull requests".
Link
Description: When highlighting your contribution, we recommend mentioning the impact that it had on the overall project. This would be helpful in highlighting your qualifications for job positions, especially if you have employment gaps. Consider using the following model to help you craft this highlight into a story:
Success verb + noun + metric + outcome.
Example: While I was reviewing some pull requests for this year's GirlScript Summer of Code, I noticed that most of them would not merge in spite of me and the owner giving approvals. So, I created a GitHub Action where pull requests automatically merge once they have passed the deployment steps(successive verb + noun), which increased productivity rates by 80%(metric + outcome).
[Screenshot here]
* Share it!: Once you've built up a portfolio of open source contributions, you can share your OpenSauced resume with others by clicking the share button in the header of your profile page. This can be especially helpful when applying for jobs, networking with other developers, or promoting your work in the open source community."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@CBID2 do you want to take this?

**Comment by CBID2** [comment]
> @CBID2 do you want to take this?

Yes I do
