### ISSUE TITLE
Bug: Wrong Positioning of the Hamburger Menu on Mobile 

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/intro#31]
### Describe the bug

The hamburger menu is positioned at the bottom of the page in mobile view:

![44474F6F-69CA-4912-BE71-3BDFEE8EE256](https://github.com/open-sauced/intro/assets/106407013/7718508f-c994-4a57-9b77-fe9de6715578)

IMHO I suggest it should be fixed at the top. 

### Reasons:
- For easy navigation.
- For visibility(Newcomers might find it difficult to locate the hamburger menu as I did and this is because most people are used to top positioned menu).

Or could there be a reason it is positioned at the top? @be

### Steps to reproduce

1. Visit https://intro.opensauced.pizza/ on mobile.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Muniir1** [comment]
@bdougie i want to fix this issue can you please asign it to me? 
.take

**Comment by bdougie** [comment]
We should discuss the fix first. This site is autogenerated from the [docsify](https://github.com/docsifyjs/docsify) template. 

I would want to avoid fixing in our site with a bandaid that could be fixed permanently by interacting and contributing with the project we use.

**Comment by BekahHW** [comment]
@RitaDee I wanted to check in here and see if you've filed an issue on the docsify repo for this.

**Comment by RitaDee** [comment]
> @RitaDee I wanted to check in here and see if you've filed an issue on the docsify repo for this.

I haven't done that yet. I can do it if you want me to.

**Comment by BekahHW** [comment]
@RitaDee I suggest taking this issue through the docsify site rather than our intro course to avoid issues with docsify updates down the line.
