### ISSUE TITLE
Feature:  Translate guestbook directions into another language

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#36]
### Type of feature

🍕 Feature

### Current behavior

 The guestbook directions are written only in English, which can make new open source contributors, especially those who have English as a second language or do not speak it all.   

### Suggested solution

In the spirit of @antonio-pedro99's suggestion in issue #16, I think it would be helpful to have the directions for the guestbook in Portuguese. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by antonio-pedro99** [comment]
> ### Type of feature
> 🍕 Feature
> 
> ### Current behavior
> The guestbook directions are written only in English, which can make new open source contributors, especially those who have English as a second language or do not speak it all.
> 
> ### Suggested solution
> In the spirit of @antonio-pedro99's suggestion in issue #16, I think it would be helpful to have the directions for the guestbook in Portuguese.
> 
> ### Additional context
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### Contributing Docs
> * [x]  I agree to follow this project's Contribution Docs

no need to be exactly in Portuguese, it can be another idioms, of course if there are ones interested

**Comment by CBID2** [comment]
> > ### Type of feature
> 
> > 🍕 Feature
> 
> > 
> 
> > ### Current behavior
> 
> > The guestbook directions are written only in English, which can make new open source contributors, especially those who have English as a second language or do not speak it all.
> 
> > 
> 
> > ### Suggested solution
> 
> > In the spirit of @antonio-pedro99's suggestion in issue #16, I think it would be helpful to have the directions for the guestbook in Portuguese.
> 
> > 
> 
> > ### Additional context
> 
> > _No response_
> 
> > 
> 
> > ### Code of Conduct
> 
> > * [x]  I agree to follow this project's Code of Conduct
> 
> > 
> 
> > ### Contributing Docs
> 
> > * [x]  I agree to follow this project's Contribution Docs
> 
> 
> 
> no need to be exactly in Portuguese, it can be another idioms, of course if there are ones interested

Yeah I know it's needed in other languages

**Comment by CBID2** [comment]
Hey @antonio-pedro99, @bdougie, and @BekahHW. I just realized that I raised this issue in the wrong repo. 🤦🏾‍♀️  Check it out [here](https://github.com/open-sauced/guestbook/issues/79)

**Comment by ivansftdejc** [comment]
Where can I Find the repository of this project?
I new on Open Source. May be I can help and learn more with this work...
