### ISSUE TITLE
Feature: Section on how to add open source experiences to your resume 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#4]
### Type of feature

📝 Documentation

### Current behavior

Not quite. It’s more of a suggestion 

### Suggested solution

Since this is an introductory guide on open source, I think it’d be a good idea to add an explainer guide for job searchers, especially those who are transitioning into non-tech career paths, on how to implement their open source experience in their resume. What do you think @BekahHW? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@CBID2 are you thinking of that we need to add more [here](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#develop-your-open-source-resume) or something else altogether?

**Comment by CBID2** [comment]
> @CBID2 are you thinking of that we need to add more [here](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#develop-your-open-source-resume) or something else altogether?

Oh thanks for adding this link @BekahHW! 😊 Now that I've seen it, it would be helpful to add tips on describing the impact that the contributions had on the overall project (e.g. increased contributor productivity rates by 30% or Brought 300 members to the project) since recruiters tend to look for that in potential candidates.

**Comment by CBID2** [comment]
> @CBID2 I think that's a really good idea. In the same way, it can help folks to figure out what to write for their highlights.
> 
> I'm thinking it should go near this section:
> 
> > Build Your Open Source Resume: From here, you'll be able to add highlights to Pull Requests and Issues that you've contributed to. You can also add a description and links to your open source resume. These will be aggregated into a single page that you can share with others, as well as a summary of your contributions that will be displayed on your public profile page.
> > Let's showcase our guestbook contribution from the previous chapter! In your profile, you'll see a "Highlights" section with a text input. When you click this, you'll be able to add a title, some thoughts, and a link to your PR. This will be displayed on your public profile page. Let's add a highlight for our guestbook contribution.
> 
> Are you interested in working on this issue?

Sure @BekahHW!

**Comment by CBID2** [comment]
Here's my [PR](https://github.com/open-sauced/intro/pull/5) @BekahHW! 😄
