### ISSUE TITLE
Feature: I'd like to add to the intro course

### ISSUE THREAD

**Issue by Lymah123** [open-sauced/intro#43]
### Type of feature

📝 Documentation

### Current behavior

Not a problem . Just introduction of additional topics.

### Suggested solution

Contributing to Documentation:

-Writing Clear and Accessible Documentation.

-Using Markup Languages (e.g., Markdown, reStructuredText).

-Versioning Documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Good idea @Lymah123. Documentation is often not talked about enough in open source.

**Comment by BekahHW** [comment]
I wonder how this would fit into the current course structure. Right now, we're looking at a general overview. This is more of an exploration of different types of contribution. 

Maybe we start a new section after the Secret Sauce section? We could call it something like "Types of Contributions," and then there would be a section on Documentation, Code, Triaging. @CBID2 what do you think?

**Comment by CBID2** [comment]
Yeah I like the idea @BekahHW. We can further organize this into subsections
##Non-coding 
- Documentation 
- graphic design
- blog writing 
-Examples of contributions that exemplify each style

- Social
## Coding contributions
- Fixing bugs
- making code  more accessible 
- Adding features 
- Examples of contributions that exemplify each style

**Comment by Lymah123** [comment]
Alright. Thanks for putting my ideas into consideration @BekahHW and @CBID2 .

I appreciate it.

One more question, can I start my research and writing on the subsection? I will give @BekahHW and @CBID2 for review on each section. Let me know your take on that.

**Comment by CBID2** [comment]
Sure @Lymah123! 😊 If you need help with find examples of contributions, let me know! 😊

**Comment by Lymah123** [comment]
Alright. Thank you.
