### ISSUE TITLE
feat: Add a contributing guide

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#45]
### Type of feature

🍕 Feature

### Current behavior

There's no contributing guide.

### Suggested solution

Since we've had some great contributions on this course and excitement around continued contributions, it's important to have a contributing guide specific to this repo. I'm thinking specifically about issue #43, we could have better supported our contributor by ensuring they knew more.

We link to the main contributing guide from the docs, but we should add specifics for this repo:

1. how to add a new section, including conventions for numbering, 
2. the use of markdown, 
3. the need to add new sections to the sidebar.
4.  how to run the project locally. I suggest two methods: using the docsify CLI or using VS Code Go Live feature.
5.  how to add translations

So I would suggest adding a contributing.md with a link to https://docs.opensauced.pizza/contributing/introduction-to-contributing/ followed by the specifics

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Oguntunjiharlimatodunola** [comment]
Hi, @BekahHW. Can I work on this issue?

**Comment by BekahHW** [comment]
It's all you @Oguntunjiharlimatodunola!

**Comment by Oguntunjiharlimatodunola** [comment]
Alright! Thank you @BekahHW .

**Comment by Oguntunjiharlimatodunola** [comment]
![Screenshot (1222)](https://github.com/open-sauced/intro/assets/109049037/0924b829-cd5a-49a5-ba89-5f0794ee1a1c)
@BekahHW , check the screenshot.
Am I on the track?

**Comment by Lymah123** [comment]
@CBID2 , this is the repo issue. I will mention you in the PR as well.
