### ISSUE TITLE
feat: adding edit this page buttons

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#46]
### Type of feature

🍕 Feature

### Current behavior

There’s no editing buttons.

### Suggested solution

I think we should add one. To stay consistent with the other repos.

![edit this page](https://github.com/open-sauced/.github/assets/105683440/0b4c664d-84d5-4c6b-a5d4-762479f8935e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Thanks @BekahHW! :)

**Comment by Ganesh1521** [comment]
Hi, I hope the following code helps you in website

 <main>
        <h2>About Us</h2>
        <p>This is some content about your website.</p>
        <button id="edit-button">Edit This Page</button>
    </main>
    
edit.js to handle javascript functionality

document.addEventListener('DOMContentLoaded', function() {
    const editButton = document.getElementById('edit-button');

   
    const editURL = 'https://your-cms-url.com/edit-page';

    editButton.addEventListener('click', function() {
       
        window.location.href = editURL;
    });
});

**Comment by CBID2** [comment]
> Hi, I hope the following code helps you in website
> 
> ## About Us
> This is some content about your website.
> 
> Edit This Page
> edit.js to handle javascript functionality
> 
> document.addEventListener('DOMContentLoaded', function() { const editButton = document.getElementById('edit-button');
> 
> ```
> const editURL = 'https://your-cms-url.com/edit-page';
> 
> editButton.addEventListener('click', function() {
>    
>     window.location.href = editURL;
> });
> ```
> 
> });

Great thanks @Ganesh1521! :)
