### ISSUE TITLE
docs: add colon for language list in course introduction

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/intro#52]
### Description

I suggest adding a colon at the end of the introductory sentence before the language list. This small but meaningful adjustment will improve the readability of the content and align it with formatting conventions.

<img width="1439" alt="Screenshot 2023-09-22 at 23 12 40" src="https://github.com/open-sauced/intro/assets/106407013/39180334-91e6-46c0-a03a-4cbd74e7832c">

Proposed Changes:

Currently, the introductory sentence reads as follows:

```Like pizza, open source is meant to be shared with everyone. Click on the links below to take this course in the following languages```

I recommend modifying it to include a colon for improved structure:

```Like pizza, open source is meant to be shared with everyone. Click on the links below to take this course in the following languages:```

This straightforward change enhances the presentation of language options, making it easier for users to access the course content in their preferred language.

### Steps to reproduce

1. Go to 'https://intro.opensauced.pizza/#/'

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@RitaDee are you up for taking on this fix?

**Comment by RitaDee** [comment]
> @RitaDee are you up for taking on this fix?

Yes I am😊

**Comment by RitaDee** [comment]
I will .take this.

**Comment by RitaDee** [comment]
What do I need to do @BekahHW?

I also noticed that there are no dependencies (package.json etc) to install.

I am having this message:

```ERROR: Permission to open-sauced/intro.git denied to RitaDee.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by RitaDee** [comment]
I have fixed it and opened a PR for the above issue.
