### ISSUE TITLE
Using Codespaces and Gitpod

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#55]
### Type of feature

🍕 Feature

### Current behavior

After helping @RitaDee with her contribution, I noticed that setting up the development environment was a bit difficult (e.g., viewing the docs site locally did not work). Since Hacktoberfest is starting Sunday, it's crucial for contributors, especially those who are new to open source, to have a somewhat easy way to get started. 

### Suggested solution

Adding links to GitHub Codespaces and Gitpod would be very helpful. It'll make it easier for contributors to step up their coding environment in a quicker fashion and to start contributing. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@BekahHW, it looks like the README doesn't mention installing `docsify` globally, i.e. `npm install docsify -g`. That's one way to run it or you can create a package.json and add `docsify` as a dependency and have a command like `npm start` that runs `docsify`.

**Comment by BekahHW** [comment]
Ok, I need to clarify here. Where is the issue? In the Intro course or the docs?

For the intro course, we have a contributing guide PR that will have directions for docsify or how to use Go Live in VS code.

If the issue is in the docs repo, then docsify won't work there, as Nick mentioned it uses docusaurus so you have to run npm ci and npm start.

**Comment by nickytonline** [comment]
Thanks for chiming in @BekahHW. If there's a PR up for how to use docsify, awesome.

**Comment by CBID2** [comment]
Thanks for clarifying @nickytonline. I mentioned this as a reason to implement links to Codespaces and Gitpod, but I already did that.
