### ISSUE TITLE
Bug: Broken links from missing files on README and on the site

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#58]
### Describe the bug

- The link to [Glossary](https://github.com/open-sauced/intro/blob/main/09-glossary.md) and [Additional Resources](https://github.com/open-sauced/intro/blob/main/08-additional-resources.md) files in the "[Additional Information](https://github.com/open-sauced/intro#additional-information)" section on the README are leading to 404. It happens because the files have been removed. They also reflected [on the website](https://intro.opensauced.pizza/#/).

- The "[Conclusion](https://intro.opensauced.pizza/#/07-conclusion)" page on the website also redirect to 404. This happens because the file changed from `07-conclusion.md` to `09-conclusion.md`.

### Steps to reproduce

1. Go to [conclusion](https://intro.opensauced.pizza/#/07-conclusion) or [additional resources](https://intro.opensauced.pizza/#/08-additional-resources) or [glossary](https://intro.opensauced.pizza/#/09-glossary) page on the website.
2. You will see a "404 - Not found".

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
@BekahHW @CBID2 I can work on this.

I need confirmation. Do we want to delete the "Additional Information" section on the README?

**Comment by CBID2** [comment]
> @BekahHW @CBID2 I can work on this.
> 
> But I need confirmation. Do we want to delete the "Additional Information" section on the README? 

Hi @adiati98. Since it is on the website already, I think deleting that section would be a good idea. It'll keep things organized.

**Comment by BekahHW** [comment]
This is fixed with @Lymah123's PR, but I need her to merge my branch into hers before her PR gets merged.

**Comment by adiati98** [comment]
Should I put this on hold for now, @BekahHW?

**Comment by BekahHW** [comment]
I think if @Lymah123 can get to it in the next day and adds it to her PR description, then it'll be fine.

**Comment by adiati98** [comment]
Got it, @BekahHW. I'll wait then 😊

**Comment by Lymah123** [comment]
Hi @BekahHW, I will check it out.

**Comment by Lymah123** [comment]
@CBID2 , one of my PRs has fixed the issue. 

#44

**Comment by Lymah123** [comment]
> @CBID2 , one of my PRs has fixed the issue.
> 
> #44

I have cross checked again, this PR has organized it. #66
