### ISSUE TITLE
Alphabetize the glossary for ease of reference

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#60]
Our [glossary](https://intro.opensauced.pizza/#/10-glossary) isn't currently organized. It would be great to provide a resource that contributors could more easily navigate.

As part of this, the contributing guidelines should be updated to let contributors know that the standard for contribution is to add it in alphabetically.

The two files that should up updated in this change are `CONTRIBUTING.md` and `10-glossary.md`

**Comment by chris-nowicki** [comment]
@BekahHW I'll take this issue :) .take

**Comment by anushka9555** [comment]
I would also like to work on this issue and try to resolve it at the earliest.

**Comment by Abhishek-90** [comment]
I am already working on the glossary part, once all the items are added to glossary, I can take up and raise another PR.

**Comment by Abhishek-90** [comment]
Should I start working on this issue? I have completed adding glossaries and merged my PR

**Comment by adiati98** [comment]
> Should I start working on this issue ? I have completed adding glossaries and merged my PR

Hi @Abhishek-90,
As you see in the assignees section at the right sidebar here, we are assigining this issue to @chris-nowicki 🙂

**Comment by adiati98** [comment]
Hi @chris-nowicki,
How is this issue going? Do you have any blockers or need our help?

If you don't want to continue working on this issue, it's totally fine.
We will unassign you and give this issue to someone else.
But please let us know :)

**Comment by chris-nowicki** [comment]
Hey! I plan on working it this week! So sorry for the delay.  I got pulled away on a business trip but now I’m back! :)On Oct 20, 2023, at 3:47 AM, Ayu Adiati ***@***.***> wrote:﻿
Hi @chris-nowicki,
How is this issue going? Do you have any blockers or need our help?
If you don't want to continue working on this issue, it's totally fine.
We will unassign you and give this issue to someone else.
But please let us know :)

**Comment by adiati98** [comment]
Noted, @chris-nowicki. 👍
Looking forward to your contribution! 😊
