### ISSUE TITLE
Add terms from ABCs of open source to glossary

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#61]
Throughout #100DaysOfOSS, we've been doing a series on the [ABCs of Open Source](https://dev.to/bekahhw/series/23962). Not all of these terms are currently in our glossary. 

Add a term or all of the terms from the series if you like, just make sure that there aren't any repeats.

These terms will be added to the `10-glossary.md` file.

**Comment by Abhishek-90** [comment]
I would like to take it up.
