### ISSUE TITLE
Update README contributing guide to use the one in this repo

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#62]
At the bottom of the readme, we link to the general contributing guide. Now that we have our new contributing guide that's specific to this repo, we should link to that instead.

**Comment by pedaars** [comment]
Can I pick this up please?

**Comment by CBID2** [comment]
> Can I pick this up please?

You've been assigned @pedaars! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)
