### ISSUE TITLE
Add .take section to CONTRIBUTING.md

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#63]
We're currently set up to have our contributors self-assign issues, but there's nothing in our contributing guide that let's contributors know.

Near the top of the CONTRIBUTING guide, add a section for this. You can find more information here: https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by pabitra0011** [comment]
Working on this issue will provide valuable experience and help me grow as a developer.
So, please can you assign me this issue.

Thank You

**Comment by ATREAY** [comment]
hey @BekahHW, can I take this issue?

**Comment by ATREAY** [comment]
hey @BekahHW, I've made the necessary updates. Could you please take a look when you have a moment?
