### ISSUE TITLE
Bug: In The section of secret sauce, Final Section Button Link is not woking Properly

### ISSUE THREAD

**Issue by kumar007ambi** [open-sauced/intro#64]
### Describe the bug

Issue : In the section of secret sauce, Final Section Button Link is not woking Properly.It always redirects to 404 page.

![Final_Section_Button_Link](https://github.com/open-sauced/intro/assets/60788663/3582221e-da47-49e6-86de-29b04ec604e6)

### Steps to reproduce

Fix : We have to update the proper page links to links.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Thanks for pointing this out @kumar007ambi. Do you want to work on this?

**Comment by pabitra0011** [comment]
Hello @kumar007ambi sir,  Please assign me this issue, I want to work with this issue.
Thank You

**Comment by CBID2** [comment]
> Hello @kumar007ambi sir, Please assign me this issue, I want to work with this issue. Thank You

You've been assigned @pabitra0011! :) Please keep the following in mind as you make your PR:

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Comment by kumar007ambi** [comment]
@CBID2 I thought I have to first raise the issue then after assigning , I have to work but you give the work some one else. I do not about these type of rule.As per my earlier Open sourced contributions where a particular person raise issue Then it must be first assignee to him not other.If the issuer not response then you can do that.

**Comment by CBID2** [comment]
> @CBID2 I thought I have to first raise the issue then after assigning , I have to work but you give the work some one else. I do not about these type of rule.As per my earlier Open sourced contributions where a particular person raise issue Then it must be first assignee to him not other.If the issuer not response then you can do that.

Hi @kumar007ambi. I apologize. In my experience, contributors raise issues and never respond, which can cause disorder. hence why I assigned the issue to someone else. In the future, I highly recommend mentioning in the comment section that you want to work on a issue.
