### ISSUE TITLE
Feature: Change 'X' button style

### ISSUE THREAD

**Issue by singodiyashubham87** [open-sauced/intro#74]
### Type of feature

🍕 Feature

### Current behavior

I want to enhance the 'x' button near search bar
![image](https://github.com/open-sauced/intro/assets/93720428/d5c5e888-2c86-4de2-b02a-2e11bc72d34e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
How do want to go about doing that @singodiyashubham87?

**Comment by geoffreylgv** [comment]
> How do want to go about doing that @singodiyashubham87?

Good question, @singodiyashubham87, the research input and close button come with the docsify theme; how will you handle it?

**Comment by singodiyashubham87** [comment]
@CBID2 @geoffreylgv  I will either scale it up a lil bit or change the whole icon itself.

**Comment by geoffreylgv** [comment]
> @CBID2 @geoffreylgv I will either scale it up a lil bit or change the whole icon itself.

@singodiyashubham87 do you mean, give a size to the `x` button, increasing it a little bit at the level of the input field?

**Comment by singodiyashubham87** [comment]
@geoffreylgv Yep!

**Comment by BekahHW** [comment]
@singodiyashubham87, if there's an issue with the docsify theme, please create an issue on their repo.

**Comment by singodiyashubham87** [comment]
@BekahHW Can you please provide that repo link?

**Comment by CBID2** [comment]
> @BekahHW Can you please provide that repo link?

Here you go @singodiyashubham87: https://github.com/docsifyjs/docsify
