### ISSUE TITLE
Feature: Add images folder and update image paths

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#76]
### Type of feature

🍕 Feature

### Current behavior

We currently have images in the root of the course and it's not information the user needs to see. 

### Suggested solution

Let's declutter our file system. Here's what needs to happen:
1. Create an images folder
2. Move all current images in the folder
3. Update the paths for all images in the repo to reflect the new location

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
I'll do it @BekahHW

**Comment by BekahHW** [comment]
@CBID2 let's see if someone else who's looking for a good first issue can take it today. If not, it's all yours tomorrow.

**Comment by CBID2** [comment]
> @CBID2 let's see if someone else who's looking for a good first issue can take it today. If not, it's all yours tomorrow. 

Sure no problem @BekahHW

**Comment by GV14982** [comment]
I'd love to take this if possible!

**Comment by GV14982** [comment]
.take

**Comment by GV14982** [comment]
Quick question, as I didn't see it in the contributing guidelines, do you have any particular commit format you use?
