### ISSUE TITLE
Feature: Add translation rules to README

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#77]
### Type of feature

🍕 Feature

### Current behavior

We currently don't have a process for translations on this repo.

### Suggested solution

You can see how we've implemented translations in the guestbook in [this pull request](https://github.com/open-sauced/guestbook/pull/116). 

Let's do the same thing here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by codewithjazzy** [comment]
I'll .take this one
