### ISSUE TITLE
Feature: add section for resolving merge conflicts

### ISSUE THREAD

**Issue by jdwilkin4** [open-sauced/intro#81]
### Type of feature

🍕 Feature

### Current behavior

Under the [How to Contribute to Open Source](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=how-to-contribute-to-open-source) section, there is a lot of helpful information but it seems to miss a section on how to resolve merge conflicts.

### Suggested solution

I think this is an important section to include because it is one of the common issues I have seen as a maintainer. 
I think adding a couple of sentences on what merge conflicts are and how to resolve them inside the VS code editor would be helpful 👍 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
Hi @jdwilkin4 , can I work on the issue?

**Comment by Lymah123** [comment]
> Hi @jdwilkin4 , can I work on the issue?

Hi @CBID2 , can I work on the issue?

**Comment by CBID2** [comment]
> > Hi @jdwilkin4 , can I work on the issue?
> 
> Hi @CBID2 , can I work on the issue?

Let’s see if @jdwilkin4 wants to first.

**Comment by Lymah123** [comment]
> > > Hi @jdwilkin4 , can I work on the issue?
> > 
> > 
> > Hi @CBID2 , can I work on the issue?
> 
> Let’s see if @jdwilkin4 wants to first.

Alright. Thank you!

**Comment by jdwilkin4** [comment]
no, I am not interested in working on this.
It's all yours @Lymah123 👍

**Comment by Lymah123** [comment]
Okay @jdwilkin4, thank you.

**Comment by Lymah123** [comment]
@CBID2 , please assign this to me.
