### ISSUE TITLE
 Feature: Want to Add Docker Files

### ISSUE THREAD

**Issue by Adidem23** [open-sauced/intro#82]
### Type of feature

🔥 Performance

### Current behavior

We can run open-sauced app by setting some configurations . 

### Suggested solution

There will  be no need of the local setup so anyone can the application 

### Additional context

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dominicduffin1** [comment]
.take

**Comment by adiati98** [comment]
Hey @Adidem23 & @dominicduffin1 

Thank you for submitting the issue & for your interest in contributing! However, we need to take a look at the issue further before we take a decision to proceed. 

We will get back to you. Thank you 🙂

**Comment by Adidem23** [comment]
@adiati98 okay for tell your review about issue . I have raised pr do review if you consider issue as valid one

**Comment by adiati98** [comment]
Hey @Adidem23,
Can you give more information about this to convince us? Why do you think we need to have this?

Also:
- Do folks need to install Docker? If so, how should we install it?
- How to run the project locally?

**Comment by Adidem23** [comment]
I will make a small video about covering this point @adiati98 .

**Comment by Adidem23** [comment]
Here is proper Guid for the adding and running docker in your repo 

1. Video about What is docker and Why It is Needed 
link : https://www.loom.com/share/0f2662c60fce4c898255d9dea9374579

2. Docker implementation in your Repository
link : https://www.loom.com/share/0f2662c60fce4c898255d9dea9374579?sid=8276ea3c-1ab8-4226-88a9-65a0aa32b6bb

**Comment by adiati98** [comment]
Thank you, @Adidem23 
We'll take a look at it. 🙂

**Comment by Adidem23** [comment]
Does it look promising to you @adiati98  . Do let me know ??

**Comment by adiati98** [comment]
Hi @Adidem23,
Thank you for your patience.

We've talked about this internally.
Because this project doesn't have complex setup and installation, and most of content in this repo are in Markdown, we don't think that Docker approach would be helpful here.

That said, we're closing your PR and closes issue #86.
However, we appreciate your ideas. Thank you. :)
