### ISSUE TITLE
Feature: Link web version of course in readme

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#89]
### Type of feature

🍕 Feature

### Current behavior

In the getting started section, we say to navigate to the intro file, but there are two options.

### Suggested solution

In [Getting Started](https://github.com/open-sauced/intro/#getting-started) we should let the reader know that there are two ways to view the course: through the repository, starting with intro, and as a website: intro.opensauced.pizza.

Both should be links.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by emontes22** [comment]
.take
