### ISSUE TITLE
Feature: Missing historical information about the development of the term, Open Source 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/intro#9]
### Type of feature

🍕 Feature

### Current behavior

I was reading through the paragraph on the [Open Source Initiative in the Brief History of Open Source](https://github.com/open-sauced/intro/blob/main/02-what-is-open-source.md#brief-history-of-open-source) and noticed that information about Christine Peterson was not present. She is the person who [coined the term "Open Source"](https://opensource.com/article/18/2/coining-term-open-source-software). In other forms of content that talk about the history of Open Source, I've noticed that Peterson is rarely mentioned, so I think it's important to add this information for the following reasons:
1. It's historically accurate
2. Open source is often a male-dominated community. According to this [report, 5.4 open source contributions were made by womxn](https://www.toptal.com/open-source/is-open-source-open-to-women), so mentioning Peterson would be very inspirational to the female and femme-identifying users of this course. 
I'd love to add this information.   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
Thanks, @CBID2 for pointing this out. It's all you!

**Comment by CBID2** [comment]
> Thanks, @CBID2 for pointing this out. It's all you!

Here it is @BekahHW, issue [#10](https://github.com/open-sauced/intro/pull/10).
