### ISSUE TITLE
docs: Move chapter "Understanding Merge Conflicts"

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#91]
## Description

The chapter [Understanding Merge Conflicts](https://intro.opensauced.pizza/#/11-understanding-merge-conflicts) currently lives at the end of the intro course, right after "Glossary".
It would make more sense if it becomes a section rather than a standalone chapter.
[How to Contribute to Open Source](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source) chapter will be suitable to hold this section.

## Suggestion

Move this section into the [How to Contribute to Open Source](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source) chapter, right after [Let's Get Practical](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) section.
This would also be in line with the suggestion in issue #81.

**Comment by adiati98** [comment]
@BekahHW @CBID2 any thought on this?

**Comment by CBID2** [comment]
> @BekahHW @CBID2 any thought on this?

That makes sense @adiati98. Can I do a PR this time?

**Comment by BekahHW** [comment]
Great idea!
