### ISSUE TITLE
docs: Update README

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#93]
## Description

There are things that can be improved in the README as follows:

1. Fix wordings.

   - OpenSauced has several websites. And currently, in the Getting Started section, we have a link to the Intro to OSS website with text "opensauced" (with no capital letters).
   - In the [Building Your Open Source Resume](https://github.com/open-sauced/intro#building-your-open-source-resume) section, there's a suggestion to read the "Building Your Open Source Resume" section in chapter 6. However, there is no section with this title. Instead, there is a [Develop your Open Source Resume](https://intro.opensauced.pizza/#/06-the-secret-sauce?id=develop-your-open-source-resume) section.

2. Update [Course Overview](https://github.com/open-sauced/intro/blob/main/README.md#course-overview) section.

   Currently, there are 5 chapters mentioned in this section. But we have 6 chapters now, including [Types of contributions](https://intro.opensauced.pizza/#/07-types-of-contributions) .

3. There is no link to our i18n guidelines in the [🤝 Contributing to this Repository](https://github.com/open-sauced/intro/blob/main/README.md#-contributing-to-this-repository) section.

## Suggestion

1. Fix wordings

   - Change the link text of the website to "Intro to Open Source course" to clarify the target website.

     ```markdown
     ... visit the [Intro to Open Source with OpenSauced](https://intro.opensauced.pizza/) website and start reading!
     ```
   - There are two options to update the title in the "Building Your Open Source Resume" section:
  
     1. Change "Building Your Open Source Resume" to "Develop your Open Source Resume" to match the course.
     2. Change the title in the course from "[Develop your Open Source Resume](https://intro.opensauced.pizza/#/06-the-secret-sauce?id=develop-your-open-source-resume)" to "Building Your Open Source Resume".

     After updating, link the section instead of linking the chapter 6.

2. Update [Course Overview](https://github.com/open-sauced/intro/blob/main/README.md#course-overview) section.

   Add the [Types of contributions](https://intro.opensauced.pizza/#/07-types-of-contributions) chapter.

3. Add a link to i18n Guidelines for translation.

**Comment by adiati98** [comment]
@BekahHW @CBID2 I need your opinion on the point 2.
Then I will .take this issue. Thank you! 😊

**Comment by CBID2** [comment]
> @BekahHW @CBID2 I need your opinion on the point 2. Then I'd like to .take this issue. Thank you! 😊

Hi @adiati98! :) I'd go with option 2. How about we merge PR #92 first to prevent merge conflicts?

**Comment by adiati98** [comment]
Thanks for the input, @CBID2 🙂

I don't think there would be merge conflicts here because this one is on chapter 6, and the PR you mentioned is on chapter 5.

**Comment by CBID2** [comment]
> Thanks for the input, @CBID2 🙂
> 
> I don't think there would be merge conflicts here because this one is on chapter 6, and the PR you mentioned is on chapter 5.

Oh ok @adiati98

**Comment by adiati98** [comment]
@BekahHW @CBID2 
Heads up, I'm changing the title and descriptions in this issue as I found some things to be improved in the README.
TIA! 😊
