### ISSUE TITLE
docs: Update "Formatting Your Highlight" Section

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#96]
## Description

The content in the "[Formatting Your Highlight](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#formatting-your-highlight)" section in the "The Secret Sauce" chapter needs to be updated because "title" is no longer required in the Highlights.

## Suggestion

Update the content in the [Formatting Your Highlight](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#formatting-your-highlight) based on the current way to add Highlights.
You can sign in and go to the [feed](https://app.opensauced.pizza/feed) page and run through how to create a Highlight to update the content.

**Comment by emontes22** [comment]
.take
