### ISSUE TITLE
docs: Replace the content in "Let's Get Practical" and "Merge Conflicts" sections with the "Getting Started" and "Update Branch & Resolve Conflicts" sections of `guestbook` repo

### ISSUE THREAD

**Issue by adiati98** [open-sauced/intro#99]
## Description

This proposal is related to [this issue](https://github.com/open-sauced/guestbook/issues/197) in the `guestbook` repo.

## Propose Solution

- Replace the content in [Merge Conflicts](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts) section with [Keeping Branch Up to Date and Resolving Merge Conflicts](https://github.com/open-sauced/guestbook?tab=readme-ov-file#keeping-branch-up-to-date-and-resolving-merge-conflicts) from the `guestbook` repo.
- Replace the content in [Let's Get Practical](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=let39s-get-practical) section with [Getting Started](https://github.com/open-sauced/guestbook?tab=readme-ov-file#getting-started) from the `guestbook` repo.
- Link these sections in the README of the `guestbook` repo.

**Comment by CBID2** [comment]
Hi @adiati98! :) I closed this issue because you mention wanting to make these changes in the guestbook repo, not the intro repo.

**Comment by adiati98** [comment]
Hey @CBID2 
I opened this issue because I will move the content from the guestbook repo to this repo, as I mentioned in the description and proposed solution. Thus, I'm working on both guestbook and intro repos.

So, I would appreciate it if you could reopen this issue as a reference to my future PR because I can't do so from my mobile app. Thank you 🙂

**Comment by CBID2** [comment]
It's reopened @adiati98. Do you mind if I do the changes you suggested for the guestbook repo? I've been wanting to update the documentation there, and you inspired me a bit. 😁

**Comment by adiati98** [comment]
Thanks, @CBID2 ! 😊

I will move those sections entirely from the guestbook to the intro course, so it would be less confusing for me if I could do it altogether as they are related.

It would be great if you could wait for my PRs to be merged, and you can propose your ideas in a new issue. 😉
